# Formål

Byvekstavtalene har mål om nullvekst i persontransport med bil: *I byområdene skal klimagassutslipp, kø, luftforurensning og støy reduseres gjennom effektiv arealbruk og ved at veksten i persontransporten tas med kollektivtransport, sykling og gange.* Trafikkutviklingen for persontransport med bil, målt med byindeks og reisevaneundersøkelser, ligger til grunn for vurderingen av måloppnåelsen i avtalene.

Datagrunnlaget for byindeksen består av “lette” biler, dvs. biler som er under 5,6 m.[^1] Byindeksen beregner endring i trafikkmengde for byområdet. Metoden er basert på tellinger fra faste trafikkregistreringspunkter fordelt på riks- og fylkesveger, samt på enkelte kommunale veger, og er ment å gi et representativt bilde av trafikkutviklingen i avtaleområdet. For hvert trafikkregistreringspunkt sammenlignes registrert trafikk dato for dato og time for time mellom to påfølgende år. Det tas hensyn til perioder hvor registreringsutstyret ikke har vært i drift, og perioder hvor trafikken i stor grad er påvirket av stenginger og omkjøringer.

[^1]: Data fra reisevaneundersøkelsen gjør det mulig å skille ut gjennomgangstrafikken, og å skille ut næringstransport med personbil («lette» biler), og kan brukes som en supplerende kilde.

Metodikken for beregning av byindeks er beskrevet nærmere i rapporten "Metodikk for beregning av byindeks", som er tilgjengelig på nettsiden

https://www.vegvesen.no/fag/trafikk/trafikkdata/indekser/byindeks.
