---
title: "Data fra bomstasjoner i Trondheim"
output: html_notebook
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE, error=FALSE}
library(tidyverse)
library(lubridate)

knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      error = FALSE)
```
 

```{r read}
# CSV file is made in "bomdata_trondheim.R"
bomdata_trondheim_maanedlig <- read.csv2("H:/Programmering/R/byindeks/data_index_raw/bomdata_trondheim_maanedlig_new.csv",
                                         stringsAsFactors = FALSE) %>% 
  dplyr::mutate(aar_maaned = lubridate::ymd(aar_maaned))
  
feltkoder <- tibble::enframe(unique(bomdata_trondheim_maanedlig$felt))

areaplot_by_class <- function(data_to_plot, station_no_from, station_no_to) {
  
  data_to_plot %>% 
    dplyr::filter(
      felt %in% feltkoder$value[station_no_from:station_no_to]) %>% 
    ggplot2::ggplot(aes(aar_maaned, trafikkvolum_andel,
                        fill = klasse, alpha)) +
    geom_area() +
    scale_fill_brewer() +
    facet_grid(stasjon ~ ., switch = "y") +
    theme_minimal() +
    theme(axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          axis.ticks.y = element_blank(),
          panel.grid = element_blank(),
          strip.text.y = element_text(angle = 180)) +
    ggtitle(label = "Relativ andel kjøretøy i klasser", 
            subtitle = "Data fra bomstasjonene som er med i byindeks for Trondheim")
  
}
```

# Andel kjøretøy med ukjent kjøretøyklasse

```{r plot1}
areaplot_by_class(bomdata_trondheim_maanedlig, 1, 5)
```


```{r plot2}
areaplot_by_class(bomdata_trondheim_maanedlig, 6, 10)
```

```{r plot3}
areaplot_by_class(bomdata_trondheim_maanedlig, 11, 15)
```


```{r plot4}
areaplot_by_class(bomdata_trondheim_maanedlig, 16, 20)
```

# Månedsindeks
```{r indeks}
# CSV file is made in "bomdata_trondheim.R"
bomindeks_trondheim_maanedlig <- read.csv2("H:/Programmering/R/byindeks/data_indexpoints_tidy/bom_maanedsindekser.csv",
                                         stringsAsFactors = FALSE) %>% 
  dplyr::mutate(aar_maaned = lubridate::ymd(aar_maaned))
  
feltkoder <- tibble::enframe(unique(bomindeks_trondheim_maanedlig$felt))

stepplot_by_class <- function(data_to_plot, station_no_from, station_no_to) {
  
  data_to_plot %>% 
    dplyr::filter(
      felt %in% feltkoder$value[station_no_from:station_no_to]) %>% 
    ggplot2::ggplot(aes(aar_maaned, indeks)) +
    geom_bar(stat = "identity") +
    facet_grid(stasjon ~ ., switch = "y") +
    theme_minimal() +
    theme(axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          axis.ticks.y = element_blank(),
          panel.grid = element_blank(),
          strip.text.y = element_text(angle = 180)) +
    ggtitle(label = "Indeks", 
            subtitle = "Data fra bomstasjonene som er med i byindeks for Trondheim")
  
}
```

```{r indeksplott1, fig.width=8, fig.height=8}
bomindeks_trondheim_maanedlig %>% 
  dplyr::filter(klasse == "Liten_bil") %>% 
  stepplot_by_class(1, 5)
```

```{r indeksplott2, fig.width=8, fig.height=8}
bomindeks_trondheim_maanedlig %>% 
  dplyr::filter(klasse == "Liten_bil") %>% 
  stepplot_by_class(6, 10)
```



```{r indeksplott3, fig.width=8, fig.height=8}
bomindeks_trondheim_maanedlig %>% 
  dplyr::filter(klasse == "Liten_bil") %>% 
  stepplot_by_class(11, 15)
```


```{r indeksplott4, fig.width=8, fig.height=8}
bomindeks_trondheim_maanedlig %>% 
  dplyr::filter(klasse == "Liten_bil") %>% 
  stepplot_by_class(16, 20)
```



