---
title: "Byindekspunkter Oslo og Akershus"
output: html_notebook
---

```{r library, include = FALSE}
library(tidyverse)
library(httr)
library(jsonlite)
library(leaflet)
library(htmlwidgets)
library(knitr)
#library(sf)
#library(mapview)
library(flextable)
#source("funksjoner_hent_nvdb_info.R")
```

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,
                      error = FALSE, cache = TRUE)
nvdb_map_url <- "https://nvdbcache.geodataonline.no/arcgis/rest/services/Trafikkportalen/GeocacheTrafikkJPG/MapServer/tile/{z}/{y}/{x}"

nvdb_map_attribution <- "NVDB, Geovekst, kommunene og Open Street Map contributors (utenfor Norge)"

nvdb_crs <- leafletCRS(crsClass = "L.Proj.CRS", code = "EPSG:25833",
  proj4def = "+proj=utm +zone=33 +ellps=GRS80 +units=m +no_defs",
  #scales = 1250*2^(16:0),
  resolutions = c(
    21674.7100160867,
    10837.35500804335,
    5418.677504021675,
    2709.3387520108377,
    1354.6693760054188,
    677.3346880027094,
    338.6673440013547,
    169.33367200067735,
    84.66683600033868,
    42.33341800016934,
    21.16670900008467,
    10.583354500042335,
    5.291677250021167,
    2.6458386250105836,
    1.3229193125052918,
    0.6614596562526459,
    0.33072982812632296,
    0.16536491406316148
  ),
  origin = c(-2500000.0, 9045984.0))
```

```{r adt, include = FALSE}
# TODO: ÅDT (med dekingsgrad) 2018 fra TD-API.
# Leser inn ÅDT (må hentes fra NVDB-API eller trafikkdata-API på sikt)
# adt <- read.csv2("adt_2017_nortraf.csv") %>% 
#   filter(Felt == "R0") %>% 
#   mutate(Stasjonnr = as.character(Tellepunkt),
#          ADT = round(ADT, digits = -2)) %>% 
#  select(Stasjonnr, ADT)
```


```{r points, include=FALSE, warning=F}
indekspunkter_oslo <- read.csv2("indekspunktene_oslo.csv")

# TODO: Legger inn kunstige punkter
indekspunkter_oslo_kunstige <- read.csv2("indekspunkter_oslo_kunstige.csv") %>% 
  dplyr::mutate(established = "Nei" )

indekspunktene_oslo <- bind_rows(indekspunkter_oslo,
                                 indekspunkter_oslo_kunstige)
```


```{r table, echo=F, include=F}
indekspunktene_oslo %>% 
  dplyr::select(name, road_reference, established) %>% 
  dplyr::arrange(road_reference) %>% 
  flextable::flextable() %>% 
  flextable::set_header_labels(name = "Navn",
                               road_reference = "Vegreferanse",
                               established = "Etablert") %>% 
  flextable::bold(part = "header") %>% 
  flextable::fontsize(size = 12, part = "all") %>% 
  flextable::font(fontname = "Lucida Sans Unicode", part = "all") %>% 
  flextable::bg(bg = "#ED9300", part = "header") %>% 
  flextable::align(part = "all") %>% 
  flextable::autofit() %>% 
  flextable::height_all(height = .2) %>% 
  flextable::padding(padding.top = .4,
                     padding.bottom = .4)
```

```{r mapcode, include=T, cache=FALSE, message=F}
pal <- colorFactor(c("navy", "red"), domain = c("Ja", "Nei"))

map.oslo <- 
  indekspunktene_oslo %>% 
  leaflet(width = "100%",
          options = leafletOptions(crs = nvdb_crs)) %>% 
  addTiles(urlTemplate = nvdb_map_url,
           attribution = nvdb_map_attribution) %>%
  addCircleMarkers(
    radius = 6,
    stroke = T,
    weight = 3,
    color = "white",
    opacity = 0.5,
    fill = T,
    fillColor = ~pal(established),
    fillOpacity = 0.7
  ) %>% 
  addLegend("bottomright",
            pal = pal,
            values = ~established,
            title = "Etablert",
            opacity = 0.7)
  #addLabelOnlyMarkers(label = ~Veg,
  #                    labelOptions = 
  #                      labelOptions(noHide = T, 
  #                                   direction = 'top', 
  #                                   textOnly = T,
  #                                   offset = c(0, 7)))

map.oslo
```


