---
title: Byindekspunkter på Nord-Jæren
output: html_notebook
---

```{r setup, include = FALSE, echo = FALSE, message=FALSE, warning=FALSE}
source("rmd_setup.R")
library(writexl)
library(DT)
library(htmltools)
```

```{r points, include = FALSE}
area_trps <- points %>% 
  dplyr::filter(traffic_type == "VEHICLE") %>% 
  dplyr::filter(municipality_name %in% c("Stavanger", "Sandnes", "Randaberg", "Sola"))

area_trps_city_index <- area_trps %>% 
  filter(trp_id %in% trp_jaeren_2016_ids$trp_id) %>% 
  mutate(byindeks = "Ja")

area_trps_not_city_index <- area_trps %>% 
  filter(!(trp_id %in% trp_jaeren_2016_ids$trp_id)) %>% 
  mutate(byindeks = "Nei")

area_trps_categorized <- bind_rows(area_trps_city_index,
                                   area_trps_not_city_index) %>% 
  # Removing trps outside city area
  filter(!(trp_id %in% c("40190V319527",
                         "22478V1814807",
                         "50233V320584",
                         "55439V320125",
                         "45995V320592"))) %>% 
  filter(validFrom < "2019-01-01")

ant_med <- nrow(filter(area_trps_categorized, byindeks == "Ja"))
ant_ute <- nrow(filter(area_trps_categorized, byindeks == "Nei"))

area_trps_categorized %>% 
  select(trp_id, name, road_reference, municipality_name, byindeks) %>% 
  writexl::write_xlsx(path = "punkter_nord_jaeren.xlsx")


trp_device <- get_trs_device() %>%
  dplyr::select(trp_id, trs_id, deviceType)

area_trps_categorized_device <- area_trps_categorized %>% 
  left_join(trp_device)

area_devices <- area_trps_categorized_device %>% 
  group_by(deviceType) %>% 
  summarise(antall = n())
```


Kartet nedenfor viser trafikkregistreringspunkter innen det aktuelle byområdet.

```{r map}
palett_stasjonstype <- 
  colorFactor(palette = c("#db3b99", "#444f55"), 
              domain = c("Ja", "Nei"))

area_trps_categorized %>%
  leaflet(width = "100%",
          height = 700,
          options = leafletOptions(crs = nvdb_crs,
                                   zoomControl = F)) %>%
  addTiles(urlTemplate = nvdb_map_url,
           attribution = nvdb_map_attribution) %>%
  addCircleMarkers(
    radius = 6,
    stroke = T,
    weight = 2,
    color = ~palett_stasjonstype(byindeks),
    opacity = 0.8,
    fill = T,
    #fillColor = ~palett_adt(adt),
    fillOpacity = 0.2,
    label = ~name
  ) %>%
  addLegend("bottomright",
            pal = palett_stasjonstype,
            values = ~byindeks,
            title = "Byindekspunkt",
            opacity = 0.7) #%>%
  # addLegend("bottomright",
  #           pal = palett_adt,
  #           values = ~adt,
  #           title = "ÅDT",
  #           opacity = 0.7,
  #           labFormat = labelFormat(big.mark = " "))
```


Antall trafikkregstreringsstasjoner i utvalget: `r  nrow(area_trps_categorized)`.

Antall med i byindeks: `r  ant_med`.

Antall ikke med i byindeks: `r  ant_ute`.

```{r table}
area_trps_categorized %>% 
  dplyr::select(name,
                road_reference, 
                municipality_name,
                byindeks) %>%
  dplyr::rename(Navn = name,
                Vegreferanse = road_reference,
                Kommune = municipality_name,
                Byindekspunkt = byindeks) %>% 
  DT::datatable(
    filter = "top",
    extensions = "Buttons",
    options = list(
      dom = "Blfrtip",
      buttons = c("excel"),
      pageLength = 100,
      lengthMenu = c(25, 50, 100),
      autoWidth = TRUE))

# area_trps_categorized %>%
#   select(name, road_reference, municipality_name, validFrom) %>%
#   arrange(road_reference) %>%
#   flextable() %>%
#   set_header_labels(name = "Navn",
#                     road_reference = "Vegreferanse",
#                     municipality_name = "Kommune",
#                     validFrom = "I Datainn fra") %>%
#   bold(part = "header") %>%
#   fontsize(size = 9, part = "all") %>%
#   font(fontname = "Lucida Sans Unicode", part = "all") %>%
#   bg(bg = "#ED9300", part = "header") %>%
#   border_remove() %>%
#   hline_top(part = "header", border = borderline) %>%
#   hline_bottom(part = "all", border = borderline) %>%
#   autofit() %>%
#   height_all(height = .2) %>%
#   padding(padding.top = .3,
#           padding.bottom = .3) %>%
#   #width(j = 5, width = 1) %>%
#   set_caption("Trafikkregistreringspunkter på Nord-Jæren.")
```

