---
title: "Byindeks"
output: html_notebook
---

```{r, echo=F, warning=FALSE, message=FALSE}
library(tidyverse)
library(httr)
library(jsonlite)
library(leaflet)
library(htmlwidgets)
library(knitr)
library(sf)
library(mapview)
#knitr::opts_chunk$set( cache = T)
```

```{r, echo=FALSE}
# Definer URI og sti ####
nvdb_url <- "https://www.vegvesen.no/nvdb/api/v2"
sti_vegobjekter <- "/vegobjekter"
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Bygg spørring etter trafikkregistreringsstasjoner per kommune

hent_kommune <- function(kommunenr) {
  api_query_536 <- paste0(nvdb_url,
                        sti_vegobjekter,
                        "/536",
                        "?inkluder=egenskaper,lokasjon")

  api_query_536_kommune <- paste0(api_query_536,
                                  "&kommune=",
                                  kommunenr,
                                  "&srid=wgs84")
  
  respons <- GET(api_query_536_kommune,
                 add_headers("X-Client" = "trafikkdatagruppa",
                             "X-Kontaktperson" = "snorre.hansen@vegvesen.no",
                             "Accept" = "application/vnd.vegvesen.nvdb-v2+json"))

  uthenta <- fromJSON(str_conv(respons$content, encoding = "UTF-8"),
                      simplifyDataFrame = T,
                      flatten = T)
  
  kommune <- bind_rows(uthenta$objekter$egenskaper, .id = "kid") %>% 
    filter(id %in% c(4585))
  
  kommunenavn <- kommune$verdi
  
  polygon <- uthenta$objekter$lokasjon.geometri.wkt
  
  svar <- list(kommunenavn, polygon)
  
  return(svar)
}

hent_trafikkregistreringsstasjon_for_omraade <- function(omraadenr) {
  # Fire siffer angir kommunenr.
  # Ett eller to siffer angir fylkenr.
  
  api_query_482 <- paste0(nvdb_url,
                        sti_vegobjekter,
                        "/482",
                        "?inkluder=egenskaper,lokasjon")
  
  omraadestreng <- ifelse(nchar(omraadenr) <= 2, 
                          "&fylke=",
                          "&kommune="
  )
  
  api_query_482_omraade <- paste0(api_query_482,
                                  omraadestreng,
                                  omraadenr,
                                  "&srid=wgs84",
                                  "&egenskap=3910=4892")
  # Over: Filtrerer på kontinuerlige stasjoner
  
  respons <- GET(api_query_482_omraade,
                 add_headers("X-Client" = "trafikkdatagruppa",
                             "X-Kontaktperson" = "snorre.hansen@vegvesen.no",
                             "Accept" = "application/vnd.vegvesen.nvdb-v2+json"))

  uthenta <- fromJSON(str_conv(respons$content, encoding = "UTF-8"),
                      simplifyDataFrame = T,
                      flatten = T)
  
  trs <- bind_rows(uthenta$objekter$egenskaper, .id = "trsid") %>% 
    filter(id %in% c(4626, 4627, 5201, 9293, 3910)) %>% 
    select(navn, verdi) %>% 
    mutate(navn = as.factor(navn)) %>% 
    group_by(navn) %>% 
    mutate(grouped_id = row_number()) %>% 
    spread(navn, verdi, drop = F) %>% 
    select(-grouped_id) %>% 
    select(1, 4, 3, 2, 5)
  
  colnames(trs) <- c("Stasjonnr", "Navn", "Status", "Nivaa", "Trafikantgruppe")
  
  vegreferanse <- bind_rows(uthenta$objekter$lokasjon.vegreferanser, 
                            .id = "trser") %>% 
    select(-trser)
  # Ta bort fylkenr, kommunenr og mellomrom, slik at vegreferansen er på kortform
  # som kan brukes direkte i spørring etter trafikkmengde i NVDB-API.
  
  koordinater <- as.data.frame(uthenta$objekter$lokasjon.geometri.wkt) %>% 
    mutate(geometri_sub = 
             str_sub(uthenta$objekter$lokasjon.geometri.wkt, 10, -2)) %>% 
    separate(geometri_sub, into = c("lat", "lon", "alt"), sep = "[[:space:]]",
             convert = T) %>% 
    select(-1)
  
  trser <- bind_cols(trs, vegreferanse, koordinater) %>% 
    #filter(Nivaa == "Kontinuerlig (Nivå 1)") %>% 
    filter(Trafikantgruppe == "Motorkjøretøy") %>% 
    filter(Status != "Nedlagt, ikke lov å bruke") %>% 
    mutate(Veg = paste0(kategori, nummer)) %>% 
    select(-Status, -Nivaa, -Trafikantgruppe, -fylke, -kommune, -kategori, -nummer,
           -status, -hp, -meter) %>% 
    mutate(Kommune = kommunenavn)

  colnames(trser) <- c("Stasjonnr", "Navn", "Vegreferanse", 
                       "lat", "lon", "alt", "Veg", "Kommune")
  
  return(trser)
}

hent_bomstasjon_for_kommune <- function(kommunenr) {
  # Laget for Trondheim
  api_query_45 <- paste0(nvdb_url,
                        sti_vegobjekter,
                        "/45",
                        "?inkluder=egenskaper,lokasjon")

  api_query_45_kommune <- paste0(api_query_45,
                                  "&kommune=",
                                  kommunenr,
                                  "&srid=wgs84")
  
  respons <- GET(api_query_45_kommune,
                 add_headers("X-Client" = "trafikkdatagruppa",
                             "X-Kontaktperson" = "snorre.hansen@vegvesen.no",
                             "Accept" = "application/vnd.vegvesen.nvdb-v2+json"))

  uthenta <- fromJSON(str_conv(respons$content, encoding = "UTF-8"),
                      simplifyDataFrame = T,
                      flatten = T)
  
  bom <- bind_rows(uthenta$objekter$egenskaper, .id = "bomid") %>% 
    filter(id %in% c(1078, 9595)) %>% 
    select(navn, verdi) %>% 
    filter(verdi != "Ferje Flakk-Rørvik") %>% 
    group_by(navn) %>% 
    mutate(grouped_id = row_number()) %>% 
    spread(navn, verdi) %>% 
    select(-grouped_id)
  
  vegreferanse <- bind_rows(uthenta$objekter$lokasjon.vegreferanser, 
                            .id = "bomer") %>% 
    filter(nummer != 715) %>% 
    select(-bomer)
  
  koordinater <- as.data.frame(uthenta$objekter$lokasjon.geometri.wkt) %>% 
    mutate(geometri_sub = str_sub(uthenta$objekter$lokasjon.geometri.wkt, 10, -2)) %>% 
    separate(geometri_sub, into = c("lat", "lon", "alt"), sep = "[[:space:]]",
             convert = T) %>% 
    select(-1) %>% 
    filter(alt != 8.79280)
  
  bomer <- bind_cols(bom, vegreferanse, koordinater) %>% 
    mutate(Veg = paste0(kategori, nummer)) %>% 
    select(-fylke, -kommune, -kategori, -nummer,
           -status, -hp, -meter) %>% 
    mutate(Kommune = kommunenavn)

  colnames(bomer) <- c("Stasjonnr", "Navn", "Vegreferanse", 
                       "lat", "lon", "alt", "Veg", "Kommune")
  
  return(bomer)
}
```

```{r, echo=FALSE}
# Leser inn ÅDT (må hentes fra NVDB-API eller trafikkdata-API på sikt)
adt <- read.csv2("adt_2017_nortraf.csv") %>% 
  filter(Felt == "R0") %>% 
  mutate(Stasjonnr = as.character(Tellepunkt),
         ADT = round(ADT, digits = -2)) %>% 
  select(Stasjonnr, ADT)
```

```{r, echo=FALSE}
# Henter inn dekningsgrad
dekning <- read.csv2("telledager_trondheim.csv") %>% 
  mutate(Stasjonnr = as.character(Tpktnr),
         Dekningsgrad = round(100 * (SUM / dager), digits = 0)) %>% 
  select(Stasjonnr, aar, Dekningsgrad)

dekning_2017 <- dekning %>% 
  filter(aar == 2017) %>% 
  mutate(Dekning_17 = Dekningsgrad) %>% 
  select(Stasjonnr, Dekning_17)

dekning_2018 <- dekning %>% 
  filter(aar == 2018) %>% 
  mutate(Dekning_18 = Dekningsgrad) %>% 
  select(Stasjonnr, Dekning_18)

```

```{r, echo=FALSE}
# Hvilke stasjonsnumre skal være med?
byindekspunkter_trondheim <- c("1600011",
                               "1600012",
                               "1600078",
                               "1600097",
                               "1600101",
                               #"1600104",
                               "1600122",
                               "1600123",
                               "1600124",
                               "1600125",
                               "1600126",
                               "1600127",
                               "1600128",
                               "1600149",
                               "1600154",
                               #"1600155",
                               "1600156",
                               "1600157",
                               "1600193",
                               "1600209",
                               "1600213",
                               "1600214",
                               "1600218",
                               "1600219",
                               "1601405",
                               #"1601416",
                               "1601418",
                               #"1601438",
                               #"1601441",
                               "1602306",
                               "1602407",
                               "1602418",
                               #"1700012",
                               "1700027",
                               "1700008",
                               #"1700029",
                               #"1700061",
                               #"1700062",
                               "51", "52", "53", "54", "55", "56", "57", "58",
                               "59", "60", "61", "62", #"63", 
                               "64", "65", "66",
                               "67", "68", "69", "72", "74", "85", "86",
                               # tre nye forslag fra kommunene:
                               "1603001", "1603002", "1603003")

```

```{r, echo=F, warning=F, message=FALSE}
# Utfører spørringer mot NVDB for aktuelle kommuner
# Trondheim 5001
kommunenr <- "5001"
kommunenavn <- hent_kommune(kommunenr)[[1]]
#kommunepolygon <- hent_kommune(kommunenr)[[2]]
kommune_trser_5001 <- hent_trafikkregistreringsstasjon_for_kommune(kommunenr) %>% 
  mutate(Type = "TRS")
kommune_bomer <- hent_bomstasjon_for_kommune(kommunenr) %>% 
  mutate(Type = "Bom")

# Melhus 5028
kommunenr <- "5028"
kommunenavn <- hent_kommune(kommunenr)[[1]]
#kommunepolygon <- hent_kommune(kommunenr)[[2]]
kommune_trser_5028 <- hent_trafikkregistreringsstasjon_for_kommune(kommunenr) %>% 
  mutate(Type = "TRS")

# Malvik 5031
kommunenr <- "5031"
kommunenavn <- hent_kommune(kommunenr)[[1]]
#kommunepolygon <- hent_kommune(kommunenr)[[2]]
kommune_trser_5031 <- hent_trafikkregistreringsstasjon_for_kommune(kommunenr) %>% 
  mutate(Type = "TRS")
kommune_bomer_5031 <- hent_bomstasjon_for_kommune(kommunenr) %>% 
  mutate(Type = "Bom")

kommunepunkter <- bind_rows(kommune_trser_5001,
                            kommune_trser_5028, 
                            kommune_trser_5031,
                            kommune_bomer,
                            kommune_bomer_5031) %>% 
  filter(!(Stasjonnr %in% 
             c("1605010", "1600211", "1600212", "1600210", 
               "1600265", "1600158", "1602315"))) 


# Legger til forslag til nye! Legge de inn i dekning og ådt.
#write.csv2(kommunepunkter, file = "kommunepunkter.csv",
#           row.names = F)
kommunepunkter_nye_forslag <- read.csv2("nye_forslag.csv",
                                        colClasses = c("character",
                                                       "character",
                                                       "character",
                                                       "numeric",
                                                       "numeric",
                                                       "numeric",
                                                       "character",
                                                       "character",
                                                       "character"))

kommunepunkter_2 <- bind_rows(kommunepunkter, kommunepunkter_nye_forslag)

kommunepunkter_trondheim_med <- kommunepunkter_2 %>% 
  filter(Stasjonnr %in% byindekspunkter_trondheim) %>% 
  mutate(Byindeks = "Ja")

kommunepunkter_trondheim_ute <- kommunepunkter_2 %>% 
  filter(!(Stasjonnr %in% byindekspunkter_trondheim)) %>% 
  mutate(Byindeks = "Nei")

kommunepunkter_trondheim <- bind_rows(kommunepunkter_trondheim_med,
                                      kommunepunkter_trondheim_ute)

# Må legge til ÅDT, hente fra NVDB
```

Tabell og kart over byindekspunktene. TRS står for trafikkregistreringsstasjon. 
Kartet viser også punkter som ikke er med i indeksen (små sirkler).

Dekningsgrad er oppgitt som prosentvis andel dager registrert i året, for 2018
gjelder tall til og med august.

# Trondheim

```{r, results='asis', echo=FALSE, message=FALSE}
# Tabell
kommunepunkter_trondheim  %>% 
  left_join(adt) %>% 
  left_join(dekning_2017) %>% 
  left_join(dekning_2018) %>% 
  select(Navn, Kommune, Veg, Type, Byindeks, ADT, Dekning_17, Dekning_18) %>% 
  arrange(Byindeks, Veg) %>% 
  kable(format.args = list(big.mark = " "))
```

```{r, warning=FALSE, echo=FALSE, include=FALSE}
pal <- colorFactor(c("navy", "red"), domain = c("TRS", "Bom"))

map.trd <- kommunepunkter_trondheim %>% 
  leaflet(width = "100%", 
          options = leafletOptions(minZoom = 0, maxZoom = 18)) %>% 
  addProviderTiles(providers$Esri.WorldStreetMap) %>% 
  addCircleMarkers(
    radius = ~ifelse(Byindeks == "Ja", 6, 3),
    color = ~pal(Type),
    weight = 3,
    opacity = 0.6,
    fill = F
  ) %>% 
  addLabelOnlyMarkers(label = ~Veg,
                      labelOptions = 
                        labelOptions(noHide = T, 
                                     direction = 'top', 
                                     textOnly = T,
                                     offset = c(0, 7))) %>% 
  addLegend("bottomright", pal = pal, values = ~Type,
    title = "Type",
    opacity = 1
  )
```

Kartet angir byindekspunkter med store sirkler, og øvrige punkter med små sirkler.

```{r, echo=FALSE}
map.trd
```
<!--
# Melhus
```{r, echo=F, warning=F, message=FALSE}
# Utfører spørringer mot NVDB for aktuelle kommuner
# Melhus 5028
kommunenr <- "5028"
kommunenavn <- hent_kommune(kommunenr)[[1]]
kommunepolygon <- hent_kommune(kommunenr)[[2]]
kommune_trser <- hent_trafikkregistreringsstasjon_for_kommune(kommunenr)

kommunepunkter_melhus_med <- kommune_trser %>% 
  filter(Stasjonnr %in% byindekspunkter_trondheim) %>% 
  filter(!(Stasjonnr %in% c("1600211", "1600212", "1600210", "1600265"))) %>% 
  mutate(Byindeks = "Ja")

kommunepunkter_melhus_ute <- kommune_trser %>% 
  filter(!(Stasjonnr %in% byindekspunkter_trondheim)) %>% 
  filter(!(Stasjonnr %in% c("1600211", "1600212", "1600210", "1600265"))) %>% 
  mutate(Byindeks = "Nei")

kommunepunkter_melhus <- bind_rows(kommunepunkter_melhus_med,
                                      kommunepunkter_melhus_ute)

# Må legge til ÅDT, hente fra NVDB
```


```{r, results='asis', echo=FALSE, message=FALSE}
# Tabell
kommunepunkter_melhus  %>% 
  left_join(adt) %>% 
  left_join(dekning_2017) %>% 
  left_join(dekning_2018) %>% 
  select(Navn, Kommune, Veg, Byindeks, ADT, Dekning_17, Dekning_18) %>% 
  arrange(Byindeks, Veg) %>% 
  kable(format.args = list(big.mark = " "))
```


```{r, warning=FALSE, echo=FALSE, include=FALSE}
map.melhus <- kommunepunkter_melhus %>% 
  leaflet(width = "100%", options = leafletOptions(minZoom = 0, maxZoom = 18)) %>% 
  addProviderTiles(providers$Esri.WorldStreetMap) %>% 
  addCircleMarkers(
    radius = ~ifelse(Byindeks == "Ja", 6, 4),
    color = "red",
    weight = 3,
    opacity = 0.6,
    fill = F
  ) %>% 
  addLabelOnlyMarkers(label = ~Veg,
                      labelOptions = 
                        labelOptions(noHide = T, 
                                     direction = 'top', 
                                     textOnly = T,
                                     offset = c(0, 7)))
```

```{r, echo=FALSE}
map.melhus
```

<!--
# Malvik
```{r, echo=F, warning=F, message=FALSE}
# Utfører spørringer mot NVDB for aktuelle kommuner
# Malvik 5031
kommunenr <- "5031"
kommunenavn <- hent_kommune(kommunenr)[[1]]
kommunepolygon <- hent_kommune(kommunenr)[[2]]
kommune_trser <- hent_trafikkregistreringsstasjon_for_kommune(kommunenr) %>% 
  mutate(Type = "TRS")
kommune_bomer <- hent_bomstasjon_for_kommune(kommunenr) %>% 
  mutate(Type = "Bom")
kommunepunkter <- bind_rows(kommune_trser, kommune_bomer)

kommunepunkter_malvik_med <- kommunepunkter %>% 
  filter(Stasjonnr %in% byindekspunkter_trondheim) %>% 
  mutate(Byindeks = "Ja")

kommunepunkter_malvik_ute <- kommunepunkter %>% 
  filter(!(Stasjonnr %in% byindekspunkter_trondheim)) %>% 
  mutate(Byindeks = "Nei")

kommunepunkter_malvik <- bind_rows(kommunepunkter_malvik_med,
                                      kommunepunkter_malvik_ute)

# Må legge til ÅDT, hente fra NVDB
```


```{r, results='asis', echo=FALSE, message=FALSE}
# Tabell
kommunepunkter_malvik  %>% 
  left_join(adt) %>% 
  left_join(dekning_2017) %>% 
  left_join(dekning_2018) %>%
  select(Navn, Kommune, Veg, Type, Byindeks, ADT, Dekning_17, Dekning_18) %>% 
  arrange(Byindeks, Veg) %>% 
  kable(format.args = list(big.mark = " "))
```


```{r, warning=FALSE, echo=FALSE, include=FALSE}
map.malvik <- kommunepunkter_malvik %>% 
  leaflet(width = "100%", options = leafletOptions(minZoom = 0, maxZoom = 18)) %>% 
  addProviderTiles(providers$Esri.WorldStreetMap) %>% 
  addCircleMarkers(
    radius = ~ifelse(Byindeks == "Ja", 6, 4),
    color = ~pal(Type),
    weight = 3,
    opacity = 0.6,
    fill = F
  ) %>% 
  addLabelOnlyMarkers(label = ~Veg,
                      labelOptions = 
                        labelOptions(noHide = T, 
                                     direction = 'top', 
                                     textOnly = T,
                                     offset = c(0, 7))) %>% 
  addLegend("bottomright", pal = pal, values = ~Type,
    title = "Type",
    opacity = 1
  )
```

```{r, echo=FALSE}
map.malvik
```
-->
<!--
# Stjørdal
```{r, echo=F, warning=F, message=FALSE}
# Utfører spørringer mot NVDB for aktuelle kommuner
# Stjørdal 5035
kommunenr <- "5035"
kommunenavn <- hent_kommune(kommunenr)[[1]]
kommunepolygon <- hent_kommune(kommunenr)[[2]]
kommune_trser <- hent_trafikkregistreringsstasjon_for_kommune(kommunenr)

kommunepunkter_stjordal_med <- kommune_trser %>% 
  filter(Stasjonnr %in% byindekspunkter_trondheim) %>% 
  filter(!(Stasjonnr %in% c("1700429"))) %>% 
  mutate(Byindeks = "Ja")

kommunepunkter_stjordal_ute <- kommune_trser %>% 
  filter(!(Stasjonnr %in% byindekspunkter_trondheim)) %>% 
  filter(!(Stasjonnr %in% c("1700429"))) %>% 
  mutate(Byindeks = "Nei")

kommunepunkter_stjordal <- bind_rows(kommunepunkter_stjordal_med,
                                      kommunepunkter_stjordal_ute)

# Må legge til ÅDT, hente fra NVDB
```


```{r, results='asis', echo=FALSE, message=FALSE}
# Tabell
kommunepunkter_stjordal  %>% 
  left_join(adt) %>% 
  left_join(dekning_2017) %>% 
  left_join(dekning_2018) %>%  
  select(Navn, Kommune, Veg, Byindeks, ADT, Dekning_17, Dekning_18) %>% 
  arrange(Byindeks, Veg) %>% 
  kable(format.args = list(big.mark = " "))
```


```{r, warning=FALSE, echo=FALSE, include=FALSE}
map.stjordal <- kommunepunkter_stjordal %>% 
  leaflet(width = "100%", options = leafletOptions(minZoom = 0, maxZoom = 18)) %>% 
  addProviderTiles(providers$Esri.WorldStreetMap) %>% 
  addCircleMarkers(
    radius = ~ifelse(Byindeks == "Ja", 6, 4),
    color = "red",
    weight = 3,
    opacity = 0.6,
    fill = F
  ) %>% 
  addLabelOnlyMarkers(label = ~Veg,
                      labelOptions = 
                        labelOptions(noHide = T, 
                                     direction = 'top', 
                                     textOnly = T,
                                     offset = c(0, 7)))
```

```{r, echo=FALSE}
#map.stjordal
```
-->

<!--
# Oslo og Akershus


```{r, echo=FALSE}
# Hvilke stasjonsnumre skal være med?
byindekspunkter_oslo_og_akershus <- c("200006",
                               "200025",
                               "200106",
                               "200119",
                               "200120",
                               "200135",
                               "200160",
                               "200200",
                               "200209",
                               "200211",
                               "200229",
                               "200801",
                               "200820",
                               "202077",
                               "202082",
                               "202182",
                               "202188",
                               "202194",
                               "202200",
                               "205310",
                               "209676",
                               "300016",
                               "300022",
                               "300030",
                               "300086",
                               "300093",
                               "300096",
                               "300108",
                               "300225",
                               "300231",
                               "300233",
                               "300349",
                               "302137")

```


```{r, echo=F}
# OSlo 3
omraadenr <- "3"
#kommunenavn <- hent_kommune(kommunenr)[[1]]
#kommunepolygon <- hent_kommune(kommunenr)[[2]]
oslo_trser <- hent_trafikkregistreringsstasjon_for_omraade(omraadenr) %>% 
  mutate(Type = "TRS")
akershus_trser <- hent_trafikkregistreringsstasjon_for_omraade("2") %>% 
  mutate(Type = "TRS")

oslo_og_akershus_trser <- bind_rows(oslo_trser, akershus_trser) %>% 
  filter(Stasjonnr %in% byindekspunkter_oslo_og_akershus) %>% 
  mutate(Byindeks = "Ja")
```

```{r, results='asis', echo=FALSE, message=FALSE}
# Tabell
punkter_oslo_og_akershus <- oslo_og_akershus_trser %>% 
  left_join(adt) %>% 
#  left_join(dekning_2017) %>% 
#  left_join(dekning_2018) %>%  
  select(Navn, Veg, ADT) %>% 
  arrange(Veg) #%>% 
#  kable(format.args = list(big.mark = " "))

write.csv2(punkter_oslo_og_akershus, file = "punkter_oslo_akershus.csv", row.names = F)
```

```{r, warning=FALSE, echo=FALSE, include=FALSE}
map.oslo <- oslo_og_akershus_trser %>% 
  leaflet(width = "100%", options = leafletOptions(minZoom = 0, maxZoom = 18)) %>% 
  addProviderTiles(providers$Esri.WorldStreetMap) %>% 
  addCircleMarkers(
    radius = ~ifelse(Byindeks == "Ja", 6, 4),
    color = "red",
    weight = 3,
    opacity = 0.6,
    fill = F
  ) %>% 
  addLabelOnlyMarkers(label = ~Veg,
                      labelOptions = 
                        labelOptions(noHide = T, 
                                     direction = 'top', 
                                     textOnly = T,
                                     offset = c(0, 7)))
```

```{r, echo=FALSE}
#map.oslo
```
-->
