---
title: "Gjennomgangstrafikk"
format: 
  html:
    css: svv.css
    number-sections: true
    toc: true
    toc-location: left
    toc-title: "Innhold"
    toc-expand: true
    df-print: paged
    self-contained: true
crossref:
  fig-title: Figur
  tbl-title: Tabell
  title-delim: .
  fig-prefix: figur
  tbl-prefix: tabell
editor: source
knitr: 
  opts_chunk: 
    echo: false
---


```{r}
#| label: setup
#| include: false
#| echo: false
#| warning: false
#| message: false
  
# Packages are loaded through sourcing rmd_setup.R
source("rmd_setup.R")
library(DT)
library(htmltools)

# Through traffic ----
through_traffic <- readr::read_csv2("through_traffic/through_traffic.csv")

# City results
trp_and_through_traffic_qmd <- readr::read_rds("through_traffic/trp_and_through_traffic.rds")
city_index_adjusted_qmd <- readr::read_rds("through_traffic/city_index_adjusted.rds")

trd_trp_and_through_traffic_qmd <- readr::read_rds("through_traffic/trd_trp_and_through_traffic.rds")
city_index_adjusted_trd <- readr::read_rds("through_traffic/city_index_adjusted_trd.rds")
```


```{r}
#| label: tromso

tromso <- readr::read_rds("city_links/city_links_tromso.rds")
```

```{r}
#| label: fig-tromso_map
#| fig-cap: "Kart over Tromsø."

tromso |>
    leaflet(
      width = "100%",
      height = 700,
      options =
        leafletOptions(
          crs = nvdb_crs,
          zoomControl = F
        )
    ) |>
    addTiles(
      urlTemplate = nvdb_map_url,
      attribution = nvdb_map_attribution
    ) |>
  
    addCircleMarkers(
      radius = 6,
      stroke = T,
      weight = 2,
      opacity = 0.8,
      fill = F,
      fillOpacity = 0.8,
      label = ~label_text
    )
```


