---
title: "Sjekk av byindeks"
output: html_notebook
---

```{r setup, include = FALSE, echo = FALSE, warning=FALSE, message=FALSE}
# Packages are loaded through sourcing rmd_setup.R
source("rmd_setup.R")

# Traffic Data API calls to get points metadata and aadt
source("get_from_trafficdata_api.R")
source("split_road_system_reference.R")
source("get_from_nvdb_api.R")

library(DT)
library(htmltools)
```



```{r get_data, include=FALSE}
# Look at details in one city at a time

# City numbers
# Bergen 8952                 10 Trond
# Buskerudbyen 1952           10 Snorre
# Grenland 955                10 Snorre
# Kristiansand og omegn 957   10 Snorre
# Nedre Glomma 953            10 Trond
# Nord-Jæren 952              10 Snorre
# Oslo 959                    10 Trond
# Tromsø 961                  10 Snorre
# Trondheim 960               12 Snorre


# Choose
index_year <- 2022
index_month <- 10 # latest published
city_number <- 8952
# End choose

reference_year <- 
  dplyr::case_when(
    city_number %in% c(
      953,
      955,
      957,
      961,
      1952
    ) ~ 2016,
    city_number %in% c(
      952
    ) ~ 2017,
    city_number %in% c(
      959,
      8952
    ) ~ 2018,
    city_number %in% c(
      960
    ) ~ 2019
  )

previous_index_years <- 
  base::seq(
    reference_year + 1,
    index_year - 1
  )

# Fetch
city_index <- 
  get_published_index_for_months(
    city_number, 
    index_year, 
    index_month
  )

pointindex <- 
  get_published_pointindex_for_months(
    city_number, 
    index_year, 
    index_month
  )

# TRD toll station index
# tolling_station_indices_prepared <-
#   readr::read_rds(
#     file = "H:/Programmering/R/byindeks/data_indexpoints_tidy/bom_maanedsindekser.rds",
#   ) |> 
#   dplyr::mutate(
#     year = lubridate::year(month_calc),
#     month = lubridate::month(month_calc),
#     class = 
#       dplyr::case_when(
#         class == "alle" ~ "total_p",
#         class == "lette" ~ "short",
#         class == "tunge" ~ "long"
#       ),
#     index_p = round(index_p, digits = 1)
#   ) |> 
#   dplyr::select(
#     trp_id,
#     year,
#     month,
#     class,
#     index = index_p
#   ) |> 
#   dplyr::filter(
#     year == index_year
#   ) |> 
#   tidyr::pivot_wider(
#     id_cols = ,
#     names_from = class,
#     names_prefix = "index_",
#     values_from = index
#   )

# For map
# tolling_station_indices_prepared_old <-
#   tolling_station_indices_prepared |> 
#   dplyr::filter(
#     month < index_month + 1
#   )
# 
# tolling_station_indices_prepared_new <-
#   tolling_station_indices_prepared |> 
#   dplyr::filter(
#     month == index_month + 1
#   )

# trd_toll_stations_meta <-
#   readr::read_rds(
#     file = "bomdata_trondheim/trd_toll_stations.rds"
#   ) |> 
#   split_road_system_reference() |> 
#   dplyr::select(
#     trp_id, 
#     name, 
#     road_reference, 
#     road_category_and_number,
#     lat, lon,
#     road_link_position
#   )

# former_pointindices <-
#   purrr::map_dfr(
#     previous_index_years,
#     ~ get_published_pointindex_for_months(city_number, .x, 12)[[2]]
#   )

city_trps <- pointindex[[1]]

# TRD: Removing Tungasletta Ystgaard
#city_trps <-
#  city_trps[! city_trps %in% c("84826V42881")]

pointindices <- pointindex[[2]]
city_name <- city_index$area_name[1]

# Point metadata from Traffic Data API
points <- 
  get_points() %>%
  dplyr::distinct(trp_id, .keep_all = T) %>%
  dplyr::select(
    trp_id, 
    name, 
    road_reference, 
    county_name,
    municipality_name, 
    lat, lon, road_link_position
  ) #%>% 
  #dplyr::mutate(name = stringr::str_to_title(name, locale = "no"))

city_trps_meta <- 
  points %>% 
  dplyr::filter(trp_id %in% city_trps) %>% 
  split_road_system_reference() %>% 
  dplyr::select(
    trp_id, 
    name, 
    road_reference, 
    road_category_and_number,
    #section_number, subsection_number, meter,
    #intersection_part_number, intersection_meter,
    #county_name, 
    #municipality_name, 
    lat, lon,
    road_link_position
  ) #|> 
  # TRD
  #dplyr::bind_rows(
  #  trd_toll_stations_meta
  #)

# TRP device types
# trp_devices <- 
#   readRDS("H:/Programmering/R/trafikkdata/trs_trp/trp_device_types.rds")
# 
# city_trp_devices <-
#   city_trps_meta %>% 
#   dplyr::left_join(
#     trp_devices,
#     by = "trp_id"
#   ) %>% 
#   dplyr::filter(
#     device_type == "EMU",
#     is.na(valid_to) | valid_to > "2020-01-01T00:00:00"
#   ) %>% 
#   dplyr::select(
#     trp_id,
#     name,
#     road_category_and_number,
#     municipality_name,
#     trs_id,
#     device_type
#   ) %>% 
#   dplyr::distinct()
# 
# city_trp_devices %>%
#   write.csv2(
#     file = "byindekspunkter_med_emu3_brg.csv",
#     row.names = FALSE
#   )

## AADT ----
adt <- 
  get_aadt_by_length_for_trp_list(city_trps)

adt_filtered <- 
  adt %>%
  dplyr::filter(length_range == "[..,5.6)") %>%
  #dplyr::mutate(length_quality = aadt_valid_length / aadt_total * 100) %>%
  #dplyr::filter(length_quality > 90) %>%
  dplyr::filter(coverage > 50) %>%
  dplyr::group_by(trp_id) %>%
  #dplyr::filter(year >= 2019) %>%
  dplyr::filter(year == max(year)) %>%
  dplyr::select(trp_id, adt = aadt_total, year)

this_citys_trps_all_adt <-
  city_trps_meta %>%
  dplyr::left_join(
    adt_filtered,
    by = "trp_id"
  )

missing_adt <-
  this_citys_trps_all_adt %>%
  dplyr::filter(is.na(adt))

fetch_adts <-
  purrr::map_dfr(
    missing_adt$road_link_position,
    ~ get_historic_aadt_by_roadlinkposition(
      roadlinkposition = .
    )
  ) |> 
  dplyr::group_by(
    road_link_position
  ) |> 
  dplyr::slice_max(
    year,
    with_ties = FALSE
  ) |> 
  dplyr::mutate(
    adt = round(aadt_total * (1 - heavy_percentage / 100), digits = -1)
  ) |> 
  dplyr::select(
    road_link_position,
    adt,
    year
  )

missing_adt_fixed <-
  missing_adt |> 
  dplyr::select(-adt, -year) |> 
  dplyr::left_join(
    fetch_adts,
    by = "road_link_position"
  )

# Finally all aadt
this_citys_trps_all_adt_final <-
  this_citys_trps_all_adt %>%
  dplyr::filter(!is.na(adt)) %>%
  dplyr::bind_rows(missing_adt_fixed) |> 
  dplyr::rename(
    year_aadt = year
  ) #|>
  # TRD (city_index_dataprep_trondheim_toll_stations.R)
  # dplyr::left_join(
  #   trd_station_type,
  #   by = "trp_id"
  # ) |> 
  # dplyr::mutate(
  #   station_type_short = stringr::str_sub(station_type, 1, 1)
  # )

readr::write_rds(
  this_citys_trps_all_adt_final,
  file = paste0(
    "index_trp_metadata/trp_",
    city_number,
    ".rds"
  )
)

# New month's pointindices
point_index_new <- 
  get_pointindices_for_trp_list(
    city_trps, 
    index_year
  )
```


```{r data_prep, message=FALSE}
city_index_prepared <- 
  city_index %>% 
  dplyr::filter(period == "month") %>% 
  dplyr::mutate(
    length_range = 
      dplyr::case_when(
        length_range == "[..,..)" ~ "alle",
        length_range == "[..,5.6)" ~ "lette",
        length_range == "[5.6,..)" ~ "tunge"
      )
  ) %>% 
  dplyr::mutate(
    road_category = 
      dplyr::case_when(
        road_category == "EUROPAVEG_RIKSVEG_FYLKESVEG_KOMMUNALVEG" ~ "Europa-, riks- og fylkesveg"
      )
  ) %>% 
  dplyr::mutate(
    index_lower = index_p - confidence_width,
    index_upper = index_p + confidence_width,
    month_object = lubridate::make_date(year = year, month = month),
    month_name = lubridate::month(month_object, label = TRUE, abbr = FALSE)
  ) %>% 
  dplyr::filter(road_category == "Europa-, riks- og fylkesveg")

pointindex_prepared <- 
  pointindices %>% 
  dplyr::filter(period == "month",
                is_excluded == FALSE,
                is_manually_excluded == FALSE) %>% 
  dplyr::select(
    trp_id, 
    year, 
    month, 
    index_total_p,
    index_total_coverage, 
    length_excluded, 
    length_coverage,
    index_short, 
    index_long
  ) #|> 
  # TRD
  #dplyr::bind_rows(
  #  tolling_station_indices_prepared_old
  #)

point_index_new_prepared <- 
  point_index_new %>% 
  dplyr::filter(day_type == "ALL",
                period == "month",
                month == index_month + 1) %>% 
  dplyr::select(
    trp_id, 
    year, 
    month, 
    index_total_p,
    index_total_coverage, 
    length_excluded, 
    length_coverage,
    index_short, 
    index_long
  ) #|> 
  # TRD
  #dplyr::bind_rows(
  #  tolling_station_indices_prepared_new
  #)

point_index_new_prepared_2 <- 
  point_index_new %>%
  dplyr::filter(day_type == "ALL",
                period == "month",
                month == index_month + 2) %>%
  dplyr::select(
    trp_id, 
    year, 
    month, 
    index_total_p,
    index_total_coverage, 
    length_excluded, 
    length_coverage,
    index_short, 
    index_long
  )
# 
# point_index_new_prepared_3 <- point_index_new %>%
#   dplyr::filter(day_type == "ALL",
#                 period == "month",
#                 month == index_month + 3) %>%
#   dplyr::select(trp_id, year, month, index_total_p,
#                 index_total_coverage, length_excluded, length_coverage,
#                 index_short, index_long)
# 
# point_index_new_prepared_4 <- point_index_new %>%
#   dplyr::filter(day_type == "ALL",
#                 period == "month",
#                 month == index_month + 4) %>%
#   dplyr::select(trp_id, year, month, index_total_p,
#                 index_total_coverage, length_excluded, length_coverage,
#                 index_short, index_long)

# point_index_new_prepared_5 <- point_index_new %>%
#   dplyr::filter(day_type == "ALL",
#                 period == "month",
#                 month == index_month + 5) %>%
#   dplyr::select(trp_id, year, month, index_total_p,
#                 index_total_coverage, length_excluded, length_coverage,
#                 index_short, index_long)

pointindex_prepared_all <- 
  dplyr::bind_rows(
    pointindex_prepared,
    point_index_new_prepared,
    point_index_new_prepared_2,
    #point_index_new_prepared_3,
    #point_index_new_prepared_4#,
    #point_index_new_prepared_5
  ) %>% 
  #dplyr::left_join(city_trps_meta) %>% 
  #dplyr::left_join(adt_filtered) %>% 
  dplyr::left_join(
    this_citys_trps_all_adt_final,
    by = "trp_id"
  ) %>% 
  dplyr::mutate(
    short_is_least = index_short < index_long,
    short_is_least_check = index_total_p >= index_short & index_total_p <= index_long,
    long_is_least_check = index_total_p >= index_long & index_total_p <= index_short,
    #short_is_least_check = dplyr::between(index_total_p, index_short, index_long),
    #long_is_least_check = dplyr::between(index_total_p, index_long, index_short),
    total_short_long_check = dplyr::case_when(
      short_is_least & short_is_least_check ~ 0, #"ok",
      short_is_least & !short_is_least_check ~ 1, #"not ok",
      !short_is_least & long_is_least_check ~ 0, #"ok",
      !short_is_least & !long_is_least_check ~ 1, #"not ok",
      ),
    diff_total_short = round(index_short - index_total_p, digits = 1)
  )
     
# For map
city_trps_new_pointindex <- 
  city_trps_meta %>% 
  dplyr::left_join(
    point_index_new_prepared,
    by = "trp_id"
  ) %>% 
  dplyr::mutate(
    label_text = 
      paste(name, ", ",
            road_category_and_number, "<br/>",
            index_total_p, " %", "<br/>",
            index_total_coverage, " %"),
    label_text = lapply(label_text, htmltools::HTML))


city_trps_new_pointindex_2 <- 
  city_trps_meta %>%
  dplyr::left_join(
    point_index_new_prepared_2,
    by = "trp_id"
  ) %>%
  dplyr::mutate(
    label_text =
      paste(name, ", ",
            road_category_and_number, "<br/>",
            index_total_p, " %", "<br/>",
            index_total_coverage, " %"),
    label_text = lapply(label_text, htmltools::HTML))
# 
# city_trps_new_pointindex_3 <- city_trps_meta %>%
#   dplyr::left_join(
#     point_index_new_prepared_3,
#       by = "trp_id"
#   ) %>%
#   dplyr::mutate(
#     label_text =
#       paste(name, ", ",
#             road_category_and_number, "<br/>",
#             index_total_p, " %", "<br/>",
#             index_total_coverage, " %"),
#     label_text = lapply(label_text, htmltools::HTML))
# 
# city_trps_new_pointindex_4 <- city_trps_meta %>%
#   dplyr::left_join(
#     point_index_new_prepared_4,
#       by = "trp_id"
#   ) %>%
#   dplyr::mutate(
#     label_text =
#       paste(name, ", ",
#             road_category_and_number, "<br/>",
#             index_total_p, " %", "<br/>",
#             index_total_coverage, " %"),
#     label_text = lapply(label_text, htmltools::HTML))

# city_trps_new_pointindex_5 <- city_trps_meta %>% 
#   dplyr::left_join(point_index_new_prepared_5)

# Widening for table view
pointindex_prepared_all_wide_total_index <- 
  pointindex_prepared_all %>% 
  dplyr::select(
    name, 
    road_category_and_number, 
    adt, 
    month, 
    index_total_p
  ) %>% 
  tidyr::pivot_wider(
    names_from = month, 
    values_from = index_total_p,
    names_prefix = "value_"
  ) %>% 
  dplyr::mutate(value_type = "index_total_p")

pointindex_prepared_all_wide_coverage <- 
  pointindex_prepared_all %>% 
  dplyr::select(name, road_category_and_number, adt, month, index_total_coverage) %>% 
  tidyr::pivot_wider(names_from = month, values_from = index_total_coverage,
                     names_prefix = "value_") %>% 
  dplyr::mutate(value_type = "index_total_coverage")

pointindex_prepared_all_wide_length_coverage <- 
  pointindex_prepared_all %>% 
  dplyr::select(name, road_category_and_number, adt, month, length_coverage) %>% 
  tidyr::pivot_wider(names_from = month, values_from = length_coverage,
                     names_prefix = "value_") %>% 
  dplyr::mutate(value_type = "length_coverage")

pointindex_prepared_all_wide_short <- 
  pointindex_prepared_all %>% 
  dplyr::select(name, road_category_and_number, adt, month, index_short) %>% 
  tidyr::pivot_wider(names_from = month, values_from = index_short,
                     names_prefix = "value_") %>% 
  dplyr::mutate(value_type = "index_short")

pointindex_prepared_all_wide_long <- 
  pointindex_prepared_all %>% 
  dplyr::select(name, road_category_and_number, adt, month, index_long) %>% 
  tidyr::pivot_wider(names_from = month, values_from = index_long,
                     names_prefix = "value_") %>% 
  dplyr::mutate(value_type = "index_long")

pointindex_prepared_all_wide_check <- 
  pointindex_prepared_all %>% 
  dplyr::select(name, road_category_and_number, adt, month, total_short_long_check) %>% 
  tidyr::pivot_wider(names_from = month, values_from = total_short_long_check,
                     names_prefix = "value_") %>% 
  dplyr::mutate(value_type = "total_short_long_check")

pointindex_prepared_all_wide_diff <- 
  pointindex_prepared_all %>% 
  dplyr::select(name, road_category_and_number, adt, month, diff_total_short) %>% 
  tidyr::pivot_wider(names_from = month, values_from = diff_total_short,
                     names_prefix = "value_") %>% 
  dplyr::mutate(value_type = "diff_total_short")

pointindex_wide <- 
  dplyr::bind_rows(
    pointindex_prepared_all_wide_total_index,
    pointindex_prepared_all_wide_coverage,
    pointindex_prepared_all_wide_length_coverage,
    pointindex_prepared_all_wide_short,
    pointindex_prepared_all_wide_long,
    pointindex_prepared_all_wide_check,
    pointindex_prepared_all_wide_diff
  ) |> 
  # split_road_system_reference() %>% 
  dplyr::rename(
    road = road_category_and_number,
  ) |> 
  dplyr::arrange(name)

# Longing :) for plot
pointindex_long <- 
  pointindex_prepared_all %>% 
  dplyr::select(trp_id:road_category_and_number)

pointindex_long_total <- 
  pointindex_long %>% 
  dplyr::select(
    trp_id, 
    year, 
    month, 
    index = index_total_p, 
    coverage = index_total_coverage,
    length_excluded, 
    name, 
    road_category_and_number
  ) %>% 
  dplyr::mutate(length_range = "total")

pointindex_long_short <- 
  pointindex_long %>% 
  dplyr::select(
    trp_id, 
    year, 
    month, 
    index_short, 
    index_long, 
    coverage = length_coverage, 
    length_excluded, 
    name, 
    road_category_and_number
  ) %>% 
  tidyr::pivot_longer(
    cols = c("index_short", "index_long"), 
    names_to = "length_range",
    values_to = "index"
  )

pointindex_long_2 <- 
  dplyr::bind_rows(
    pointindex_long_total,
    pointindex_long_short
  ) %>% 
  dplyr::mutate(
    length_range = 
      dplyr::case_when(
        length_range == "total" ~ "alle",
        length_range == "index_short" ~ "lette",
        length_range == "index_long" ~ "tunge"
      )
  ) %>% 
  dplyr::mutate(
    month_object = lubridate::make_date(year = year, month = month),
    month_name = lubridate::month(month_object, label = TRUE, abbr = FALSE)
  )
```



## Byindeks per måned så langt for `r city_name`

```{r city_index, message=FALSE, fig.width=12}
month_start = lubridate::make_date(year = 2022, month = 1)
month_end = lubridate::make_date(year = 2022, month = 12)

full_year_x_axis <- c(month_start, month_end)

city_index_prepared %>% 
  ggplot2::ggplot(aes(x = month_object, y = index_p, color = length_range)) +
  ggplot2::geom_line() +
  ggplot2::geom_point(size = 4) +
  theme_light() +
  theme(axis.text.x = element_text(angle = 90),
        panel.grid.minor.x = element_blank(),
        legend.position = "bottom") +
  scale_x_date(breaks = scales::breaks_width("months"),
               labels = scales::label_date("%b"),
               limits = full_year_x_axis) +
  scale_color_manual(values = c("alle" = "#008ec2",
                                "lette" = "#ed9300",
                                "tunge" = "#444f55"),
                     name = "Kjøretøyklasse") +
  labs(x = NULL, y = "Endring i trafikkmengde (%) \n",
       caption = "Data: Statens vegvesen og fylkeskommunene") +
  ggtitle("Estimert endring i trafikkmengde",
          subtitle = "Trafikkmengde i år sammenlignet med i fjor")
```



## Punktindeksene for den nye måneden

```{r map_trp_index, message=FALSE}
city_trps_new_pointindex %>% 
  dplyr::rename(index = index_total_p) %>% 
  create_pointindex_map()
```


```{r map_trp_index_2, message=FALSE}
city_trps_new_pointindex_2 %>%
  dplyr::rename(index = index_total_p) %>%
  create_pointindex_map()
```

```{r map_trp_index_3, message=FALSE}
# city_trps_new_pointindex_3 %>%
#   dplyr::rename(index = index_total_p) %>%
#   create_pointindex_map()
```

```{r map_trp_index_4, message=FALSE}
# city_trps_new_pointindex_4 %>%
#   dplyr::rename(index = index_total_p) %>%
#   create_pointindex_map()
```

```{r map_trp_index_5, message=FALSE}
# city_trps_new_pointindex_5 %>% 
#   dplyr::rename(index = index_total_p) %>% 
#   create_pointindex_map()
```

## Kurver per punkt for totaltrafikk

```{r pointindex_sparkline, fig.height=12, fig.width=10}
pointindex_plot <- pointindex_prepared_all %>% 
  ggplot2::ggplot(aes(x = month, y = index_total_p, color = name)) +
  geom_line() +
  scale_x_discrete(breaks = seq(1, index_month + 1, 1)) +
  theme_minimal() +
  theme(legend.position = "bottom")

pointindex_plot %>% plotly::ggplotly(width = 900, height = 700)
```



## Punktsjekk

```{r point_plot, message=FALSE, fig.width=12}
# point_number <- 1
# trp_id_here <- city_trps_meta$trp_id[point_number]
# 
# trp_name <- city_trps_meta %>% 
#   dplyr::filter(trp_id == trp_id_here) %>% 
#   dplyr::select(name, road_category_and_number) %>% 
#   stringr::str_glue_data("{name}, {road_category_and_number}")
# 
# pointindex_long_2 %>% 
#   dplyr::filter(trp_id == trp_id_here) %>% 
#   ggplot2::ggplot(aes(x = month_object, y = index, color = length_range)) +
#   ggplot2::geom_line() +
#   ggplot2::geom_point(aes(alpha = coverage), size = 4) +
#   theme_light() +
#   theme(axis.text.x = element_text(angle = 90),
#         panel.grid.minor.x = element_blank(),
#         legend.position = "bottom") +
#   scale_x_date(breaks = scales::breaks_width("months"),
#                labels = scales::label_date("%b")) +
#   scale_color_manual(values = c("alle" = "#008ec2",
#                                 "lette" = "#ed9300",
#                                 "tunge" = "#444f55"),
#                      name = "Kjøretøyklasse") +
#   scale_alpha(name = "Dekningsgrad") +
#   labs(x = NULL, y = "Endring i trafikkmengde (%) \n",
#        caption = "Data: Statens vegvesen") +
#   ggtitle(trp_name,
#           subtitle = "Trafikkmengde i år sammenlignet med i fjor")

# Notes
```

```{r table_trp_consistency}
pointindex_wide %>%
  DT::datatable(
    filter = "top",
    options = list(
      dom = "Blfrtip",
      pageLength = 21,
      lengthMenu = c(21, 42, 70),
      autoWidth = TRUE))
```


```{r exclusion_notes}
# BRG
# Nordvik 11,12
# Røykenes 11,12
# Fana v kirkevoll 11,12
# Vallaheiane 11,12
# Troldhaugtunnelen - Lagunen 11,12
# Lagunen - Troldhaugtunnelen 11,12
# Nesttuntunnelen 11,12
# Alle disse pga ny Ev 39 Svegatjørn - Rådal åpnet 31. oktober 2022. Må holdes utenfor tom okt 23.
# Torget 10

```

