---
title: "Byindeks med bomstasjoner på Nord-Jæren"
format: 
  html:
    css: svv.css
    page-layout: full
    number-sections: true
    toc: true
    toc-location: left
    toc-title: "Innhold"
    toc-expand: true
    toc-depth: 2
    df-print: paged
    self-contained: true
crossref:
  fig-title: Figur
  tbl-title: Tabell
  title-delim: .
  fig-prefix: figur
  tbl-prefix: tabell
editor: source
knitr: 
  opts_chunk: 
    echo: false
---

```{r}
#| label: setup
#| include: false
#| echo: false
#| warning: false
#| message: false
  
base::Sys.setlocale(locale = "nb.utf8")
svv_background_color <- "#F5F5F5"

library(tidyverse)
library(flextable)
library(sf)
library(htmltools)
library(leaflet)
library(RColorBrewer)

source("H:/Programmering/R/byindeks/leaflet_nvdb_map_setup.R")
source("H:/Programmering/R/byindeks/traffic_link_functions.R")
source("H:/Programmering/R/byindeks/index_report_functions.R")

flextable::set_flextable_defaults(
  decimal.mark = ",",
  big.mark = " ",
  na_str = ""
)
```


```{r}
#| label: data

point_indexes_for_map_updated_example <- 
  readr::read_rds(
    "representativity/nj_updated_example_with_toll.rds"
  ) |> 
  dplyr::rename(datakilde = source)

palett_datakilde <-
    leaflet::colorFactor(
      palette = c("#7e03a8", "#f89540"),
      domain = c("AutoPASS", "Trafikkregistrering")
    )

```



# Nytt regneeksempel med bomstasjoner


## Okt17-sep18 til okt18-sep19
```{r}
#| label: map_improved_toll_1

# Given a df with info on each index point, including toll stations:
# - name
# - latlon
# - stationtype
# - percentage change

# map <-
  point_indexes_for_map_updated_example |>
    dplyr::filter(
      reference_period == "okt17_sep18"
    ) |> 
    leaflet::leaflet(
      width = "100%",
      height = 1e3,
      options =
        leafletOptions(
          crs = nvdb_crs,
          zoomControl = F
        )
    ) |>
    leaflet::addTiles(
      urlTemplate = nvdb_map_url,
      attribution = nvdb_map_attribution
    ) |>
    leaflet::addCircleMarkers(
      lng = ~lon,
      lat = ~lat,
      radius = 11,
      stroke = T,
      weight = 4,
      color = ~palett_datakilde(datakilde),
      opacity = 0.9,
      fill = T,
      fillOpacity = 0.8,
      # label = ~indeks,
      labelOptions = 
        leaflet::labelOptions(
          noHide = TRUE, 
          textOnly = TRUE, 
          textsize = "16px",
          direction = "top",
          style = base::list(
            "font-weight" = "bold"
          )
        )
    ) |>
    leaflet::addLegend(
      position = "bottomleft",
      pal = palett_datakilde,
      values = ~datakilde,
      title = "Datakilde",
      opacity = 0.7
    ) 
```


## Okt18-sep19 til 2023
```{r}
#| label: map_improved_toll_2

# Given a df with info on each index point, including toll stations:
# - name
# - latlon
# - stationtype
# - percentage change

# map <-
  point_indexes_for_map_updated_example |>
    dplyr::filter(
      reference_period == "okt18_sep19"
    ) |> 
    leaflet::leaflet(
      width = "100%",
      height = 1e3,
      options =
        leafletOptions(
          crs = nvdb_crs,
          zoomControl = F
        )
    ) |>
    leaflet::addTiles(
      urlTemplate = nvdb_map_url,
      attribution = nvdb_map_attribution
    ) |>
    leaflet::addCircleMarkers(
      lng = ~lon,
      lat = ~lat,
      radius = 11,
      stroke = T,
      weight = 4,
      color = ~palett_datakilde(datakilde),
      opacity = 0.9,
      fill = T,
      fillOpacity = 0.8,
      # label = ~indeks,
      labelOptions = 
        leaflet::labelOptions(
          noHide = TRUE, 
          textOnly = TRUE, 
          textsize = "16px",
          direction = "top",
          style = base::list(
            "font-weight" = "bold"
          )
        )
    ) |>
    leaflet::addLegend(
      position = "bottomleft",
      pal = palett_datakilde,
      values = ~datakilde,
      title = "Datakilde",
      opacity = 0.7
    ) 
```


## 2023 og framover
```{r}
#| label: map_improved_toll_3

# Given a df with info on each index point, including toll stations:
# - name
# - latlon
# - stationtype
# - percentage change

# map <-
  point_indexes_for_map_updated_example |>
    dplyr::filter(
      reference_period == "jan23_des23"
    ) |> 
    leaflet::leaflet(
      width = "100%",
      height = 1e3,
      options =
        leafletOptions(
          crs = nvdb_crs,
          zoomControl = F
        )
    ) |>
    leaflet::addTiles(
      urlTemplate = nvdb_map_url,
      attribution = nvdb_map_attribution
    ) |>
    leaflet::addCircleMarkers(
      lng = ~lon,
      lat = ~lat,
      radius = 11,
      stroke = T,
      weight = 4,
      color = ~palett_datakilde(datakilde),
      opacity = 0.9,
      fill = T,
      fillOpacity = 0.8,
      # label = ~indeks,
      labelOptions = 
        leaflet::labelOptions(
          noHide = TRUE, 
          textOnly = TRUE, 
          textsize = "16px",
          direction = "top",
          style = base::list(
            "font-weight" = "bold"
          )
        )
    ) |>
    leaflet::addLegend(
      position = "bottomleft",
      pal = palett_datakilde,
      values = ~datakilde,
      title = "Datakilde",
      opacity = 0.7
    ) 
```