---
title: "Punktindekser i VTI"
output: html_notebook
---

```{r setup, include = FALSE, echo = FALSE, warning=FALSE, message=FALSE}
# Packages are loaded through sourcing rmd_setup.R
source("rmd_setup.R")

# Traffic Data API calls to get points metadata and aadt
source("get_from_trafficdata_api.R")
source("split_road_system_reference.R")
source("get_from_nvdb_api.R")
library(rstatix)
```


```{r get_data}
points <- get_points() %>%
  dplyr::distinct(trp_id, .keep_all = T) %>%
  dplyr::select(trp_id, name, road_reference, county_name, county_geono,
                municipality_name) %>% 
  dplyr::mutate(name = stringr::str_to_title(name, locale = "no")) %>%
  split_road_system_reference() %>% 
  dplyr::select(trp_id, name, road_category, 
                county_geono) %>% 
  dplyr::mutate(road_category = dplyr::case_when(
    road_category == "F" ~ "F",
    road_category == "E" ~ "R",
    road_category == "R" ~ "R"
  ))

pointindex <- get_published_pointindex_paginated(962, 2020, 1)

pointindices <- pointindex[[2]]

pointindices_all <- pointindices %>% 
  dplyr::filter(day_type == "ALL",
                is_excluded == FALSE,
                is_manually_excluded == FALSE,
                period == "month",
                !is.na(index_total_p)) %>% 
  dplyr::select(trp_id, year, month, period, index_total_p) %>% 
  dplyr::left_join(points)
```


```{r analyses}
#pointindices_all_summary <- 
pointindices_all %>% 
  dplyr::group_by(county_geono, road_category) %>% 
  dplyr::summarise(no_points = n(),
                   mean = mean(index_total_p),
                   median = median(index_total_p),
                   min = min(index_total_p),
                   max = max(index_total_p),
                   sd = sd(index_total_p),
                   se = sd / sqrt(no_points)) %>% 
  dplyr::mutate(dplyr::across(is.numeric, ~round(.x, digits = 1)))
```


```{r density_plot, fig.width=6.5, fig.height=7}
#pointindices_all_summary <- 
pointindices_all %>% 
  dplyr::group_by(county_geono, road_category) %>% 
  ggplot2::ggplot(aes(x = index_total_p, color = road_category)) +
  geom_density() +
  facet_grid(rows = vars(county_geono)) +
  theme_light()
```

```{r qqplot, fig.width=6.5, fig.height=7}
#pointindices_all_summary <- 
pointindices_all %>% 
  dplyr::group_by(county_geono, road_category) %>% 
  ggplot2::ggplot(aes(sample = index_total_p, color = road_category)) +
  geom_qq() +
  facet_grid(rows = vars(county_geono)) +
  theme_light()
```


```{r test_normality}
pointindices_all %>% 
  dplyr::group_by(county_geono, road_category) %>% 
  rstatix::shapiro_test(index_total_p)
```

