### Nord-sør-snitt
Ser vi på punktenes plassering, er det naturlig å se enkelte i sammenheng. F.eks. utgjør de fire punktene Ballestadhøgda, Elstrømbrua, Sandviksvegen og Smieøya et nord-sør-snitt i Skien. På samme måte er det et snitt for de tre punktene Borgestad, Lensmannsdalen og Bjørnetvedtvegen X Trommedalsvegen. I disse snittene bør derfor alle punktene inngå i perioder hvor trafikkfordelingen mellom de er utenfor det normale, for å unngå skjevheter i trafikken som fanges opp.

### Porsgrunntunnelen stengt
I perioden hvor Porsgrunnstunnelen var stengt (23.04.2019-10.12.2019), er punktene Sverresgate og Menstadbrua tatt ut da mye av trafikken gikk her. Borgestad er inkludert, da denne veies opp av Lensmannsdalen og Porsgrunnbrua, men Bjørntvedtvegen X Trommedalsvegen er holdt utenfor slik at trafikken som fanges opp blir omtrent likt på begge sider av vegnettet. 

### Bambletunnelen stengt
I perioden hvor Bambletunnelen på E18 var stengt (21.04.2017 - 31.08.2018), er punktet ved Høgenheitunnelen tatt ut fordi mye av trafikken gikk her. Men lengre nord vil de tre punktene Svanvik, Brattåstunnelen syd og Skjelsvik fange opp totaltrafikken.

### Brevikbrua stengt
I perioden april 2021 - april 2022 er Brevikbrua helt eller delvis stengt og dette medfører omfordeling av trafikken i området som slår skjevt ut på trafikkregistreringspunktene. Derfor er punktene Høgenheitunnelen og Bambletunnelen syd utelatt i denne perioden og ett år etterpå.

### Porsgrunnbrua stengt
I juni 2022 var Porsgrunnbrua stengt, men trafikkregistreringspunktene omrking var operasjonelle slik at det totale trafikkbildet ble fanget opp.