### Anleggsarbeid på Fv 6680 Tillerbrua - Klæbu
Det har i flere perioder vært anleggsarbeid med helt stengt veg på Fv 6680 mellom Tillerbrua og Klæbu sentrum. Trafikken på denne strekningen har i disse periodene i stedet gått over Fv 704 forbi Torgårdsletta. Til sammen fanger de to bomstasjonene her opp den totale trafikken mellom Trondheim og Klæbu.


### Bygging av Nydalsbrua ved Sluppen
Den første trafikkomleggingen av betydning i dette byggeprosjektet var stenging av nordgående avkjøring fra E6 ved Kroppan til Rv 706 (kryssnummer 35). Trafikken som vanligvis benyttet denne avkjøringen, måtte i stedet benytte avkjøring i kryssnummer 37 ved Nidarvoll og Sluppen og kjøre tilbake over Sluppen bru. Denne trafikken kom da tilbake til punktene bomstasjonen Bjørndalen eller Oslovegen som normalt, men har i tillegg passert bomstasjonen Nord for Sluppen bru. Dette medførte en liten økning i antall passeringer på denne bomstasjonen som gjenspeiler en noe forlenget kjørerute for denne trafikken, og som derfor er beholdt i datagrunnlaget.

Den neste store trafikkomleggingen skjedde 19. mars 2021 med stengingen av Rv 706 rett sør for Sluppen bru. Dette påvirket direkte bomstasjonen Bjørndalen som ikke har noe data for denne perioden. Bomstasjonen Nord for Sluppen bru og Oslovegen var i denne perioden på samme strekning (ingen kryss mellom) og derfor er kun bomstasjonen Nord for Sluppen bru beholdt i datagrunnlaget.

5. mai 2021 ble Rv 706 ved Sluppen bru stengt på grunn av fare for ras, og vegen forble stengt i en periode mens forholdene ble utbedret. I denne perioden er punktet Oslovegen og bomstasjonen Nord for Sluppen bru helt uten trafikk. I tillegg er trafikken gjennom Marienborgtunnelen en del redusert. Det er rimelig å anta at trafikken som normalt går forbi disse punktene velger omkjøringsruter som er dekket av andre punkter.

23. juni ble Rv 706 gjenåpnet nord for Sluppen bru, før den igjen ble stengt i perioden 1. juli til 14. august.

21. august ble Rv 706 gjenåpnet også sør for Sluppen bru.

Fra 3. januar 2022 og til sommeren 2023 er Rv 706 stengt nord for Sluppen bru. I denne perioden er det kun bomstasjonen Nord for Sluppen bru som bidrar med data til indeksen, og ikke bomstasjonen Bjørndalen eller Oslovegen.


### Bygging av Saupstadbrua
I perioden 14. november 2021 til 29. april 2022 er Fv 6682 i Bjørndalen stengt like nord for krysset med Fv 6688 grunnet bygging av ny gang- og sykkelbru. Dette vil i liten grad påvirke byindekspunktene.


### Bygging av Gryta parkeringskjeller
I perioden fra november 2020 til november 2022 foregår det byggearbeider ved Fv 6692 ved Gryta utenfor Trondheim sentralstasjon. Dette påvirker trafikken ved punktene Jernbanebrua og Brattørbrua. Det antas at disse to punktene oppveier hverandre i byggeperioden, da mye av trafikken som normalt går over Jernbanebrua nå går over Brattørbrua i stedet. En større omlegging av trafikken begynte i februar 2021. I månendene desember 2021 til februar 2022 var punktet Jernbanebrua ute av drift og derfor er også Brattørbrua ekskludert fra datagrunnlaget for at ikke trafikkomleggingen skal påvirke byindeks ensidig som en økning i. Fra og med mars 2022 er det sammenlignbare forhold med fjoråret, slik at kun Brattørbrua er med i datagrunnlaget igjen.


