Noen trafikkregistreringspunkter må ses i sammenheng når det oppstår hendelser på vegnettet som medfører omkjøringsruter. 


### Strømsåstunnelen stengt i januar og februar 2017

Når Strømsåstunnelen var stengt i januar og februar 2017, var punktet her uten trafikk og ble helt ekskludert fra indeksen i denne perioden. Da gikk trafikken i stedet på parallellveiene og følgende punkter fikk dermed en økning i trafikken: Bj. Bjørnsonsgt., Kreftingsgate, Øvre Sund bru, Gulskogen, Landfalløya bru syd, Travbanen, Herstrøm og Daler. Den aktuelle perioden er derfor ekskludert også for disse punktene for å unngå at punktene måler en ensidig økning, når det ikke er tilsvarende nedgang på punktet i Strømsåstunnelen.

### Ny Ev 134 forbi Kongsberg
3. juli 2020 ble ny Ev 134 åpnet forbi Kongsberg. Punktene Gamle KOngsnerg Kro og Veungsdalen som ligger der hvor Ev 134 gikk tidligere, men som nå ligger på fylkesveg, tas ut av byindeksen ett år for å unngå at trafikkomleggingen slår ut som en generell nedgang i trafikken i området.

### Tiltak mot koronaviruspandemien
Fra mars 2020 er trafikken i stor grad påvirket at tiltak mot spredningen av det nye koronaviruset. Trafikken varierer i takt med de til enhver tid gjeldende tiltak.