### Ny bomring
38 nye bomstasjoner ble satt i drift 1. oktober 2018 i Stavanger sentrum, Sandnes sentrum, Stavanger lufthavn Sola, Forus, Risavika og på grensen mellom Stavanger og Randaberg. Dette førte til noe omfordeling av trafikken i området.

### Åpning av Ryfast
Åpningen av Ryfast ble gjort 30. desember 2019 (Ryfylketunnelen) og 22. april 2020 (Eiganestunnelen og Hundvågtunnelen). Dette førte til omfordeling av trafikken på flere veger i området. Blant annet ble deler av gamle Ev39 omklassifisert til Fv440.

Trafikkregistreringspunkter som direkte er påvirket av dette:

- Bybrua sør, Fv 4566.
- Storhaugtunnelen, Fv 4564.
- Kannik, Fv 441.

Disse er utelatt fra indeksen i ett år fra åpningen.

### Vedlikeholdsarbeid i Byhaugtunnelen
I perioden 23.11.2020 til 01.03.2022 er Ev 39 Byhaugtunnelen (Ytre ringveg vest) stengt på grunn av vedlikeholdsarbeid. Dette fører til noe økt trafikk i Fv 4570 Randabergveien, og noe redusert trafikk på Fv 440 ved Lassa. Disse to trafikkregistreringspunktene antas å oppveie hverandre i denne perioden.