---
title: "TRP i VTI"
format: 
  html:
    css: svv.css
    number-sections: true
    toc: true
    toc-location: left
    toc-title: "Innhold"
    toc-expand: true
    df-print: paged
    self-contained: true
crossref:
  fig-title: Figur
  tbl-title: Tabell
  title-delim: .
  fig-prefix: figur
  tbl-prefix: tabell
editor: source
knitr: 
  opts_chunk: 
    echo: false
---


```{r}
#| label: setup
#| include: false
#| echo: false
#| warning: false
#| message: false
  
# Packages are loaded through sourcing rmd_setup.R
source("rmd_setup.R")
library(DT)
library(htmltools)
library(sf)
```


```{r}
#| label: data

trp_for_vti_chosen <- readr::read_rds("new_vti/vti_trp_chosen.rds")
links_chosen <- readr::read_rds("new_vti/vti_links_chosen.rds")
county_table <- readr::read_rds("new_vti/county_table.rds")
country_table <- readr::read_rds("new_vti/country_table.rds")

# Choose one county to look at:
county_chosen <- c(8, 9, 10) # geonumber 1:15 
# Do not leave Oslo (3) alone

trp_for_vti_chosen_here <-
  trp_for_vti_chosen |> 
  dplyr::filter(
    county_geono %in% county_chosen
  )

trp_for_vti_aadt_R <- 
  trp_for_vti_chosen_here |> 
  dplyr::filter(road_category == "R")

trp_for_vti_aadt_F <- 
  trp_for_vti_chosen_here |> 
  dplyr::filter(road_category == "F")

links_in_county <-
  links_chosen |> 
  dplyr::filter(
    county_id %in% unique(trp_for_vti_chosen_here$county_no)
  )

palett_adt <-
 leaflet::colorNumeric(
   palette = "Greens",
   domain = NULL
  )

link_color_keep <-
  leaflet::colorFactor(
    palette = c("#ed1c2e", "#0000ff"),
    domain = c(TRUE, FALSE),
    levels = c(TRUE, FALSE)
  )
```


# Fylke per vegkategori
```{r}
#| label: tbl-county
#| tbl-cap: "T_a er trafikkarbeid i millioner km."

# TODO: add road lengths
county_table |> 
  dplyr::select(
    Fylke = county_name,
    Vegkat = road_category,
    n_trp,
    T_a = traffic_work_mill_km,
    T_a_VTI_prosent = measured_percentage_of_traffic_work
  ) |> 
  dplyr::mutate(
    T_a = round(T_a)
  ) |> 
  DT::datatable(
    rownames = FALSE,
    filter = "none",
    options = list(
      dom = "t",
      pageLength = 30,
      autoWidth = TRUE))
```


# Norge per vegkategori
```{r}
#| label: tbl-country
#| tbl-cap: "T_a er trafikkarbeid i millioner km."

# TODO: add road lengths
country_table |> 
  dplyr::select(
    Vegkat = road_category,
    n_trp,
    T_a = traffic_work_mill_km,
    T_a_VTI_prosent = measured_percentage_of_traffic_work
  ) |> 
  dplyr::mutate(
    T_a = round(T_a)
  ) |> 
  DT::datatable(
    rownames = FALSE,
    filter = "none",
    options = list(
      dom = "t",
      pageLength = 30,
      autoWidth = TRUE))
```


# Kart
```{r}
#| label: fig-map

trp_for_vti_chosen_here |> 
  leaflet(
    width = "100%",
    options = leafletOptions(
      crs = nvdb_crs,
      zoomControl = TRUE
    )
  ) |> 
  addTiles(
    urlTemplate = nvdb_map_url,
    attribution = nvdb_map_attribution
  ) |> 
  addCircleMarkers(
    data = trp_for_vti_aadt_R,
    group = "R",
    radius = 6,
    stroke = T,
    weight = 2,
    color = "#58b02c",
    opacity = 0.8,
    fill = T,
    fillColor = ~palett_adt(adt),
    fillOpacity = 0.8,
    label = ~trp_label
  ) |> 
  addCircleMarkers(
    data = trp_for_vti_aadt_F,
    group = "F",
    radius = 6,
    stroke = T,
    weight = 2,
    color = "#008ec2",
    opacity = 0.8,
    fill = T,
    fillColor = ~palett_adt(adt),
    fillOpacity = 0.8,
    label = ~trp_label
  ) |> 
  addPolylines(
    data = links_in_county,
    opacity = 0.8,
    #fill = T,
    color = ~link_color_keep(to_keep),
    highlightOptions = highlightOptions(
      bringToFront = TRUE,
      sendToBack = FALSE,
      color = "#000000",
      opacity = 0.6
      )
    ) |> 
  addLegend(
    "bottomright",
    pal = palett_adt,
    values = ~adt,
    title = "ÅDT",
    opacity = 0.7,
    labFormat = labelFormat(big.mark = " ")
  ) |> 
  addLegend(
    "bottomright",
    pal = link_color_keep,
    values = ~links_in_county$to_keep,
    title = "I fjor",
    opacity = 0.7
  ) |> 
  addLayersControl(
    overlayGroups = c("F", "R"),
    options = layersControlOptions(collapsed = FALSE)
  )
```

