---
title: "Vegtrafikkindekspunkter"
output: html_notebook
---

Trafikkregistreringspunkter som skal benyttes i Vegtrafikkindeksen.

```{r setup, message=FALSE, warning=FALSE, results='hide'}
source("H:/Programmering/R/byindeks/rmd_setup.R")
source("H:/Programmering/R/byindeks/split_road_system_reference.R")
source("H:/Programmering/R/byindeks/get_from_trafficdata_api.R")

library(DT)
library(htmltools)
library(readxl)
```

```{r get_trp, results='hide', message=FALSE}
trp_for_vti <- get_points()

trp_for_vti_tidy <- trp_for_vti %>% 
  dplyr::select(trp_id, name, traffic_type, registration_frequency,
                county_geono, county_name, municipality_name,
                road_reference,
                road_link_position, 
                lat, lon, valid_from = validFrom,
                operational_status, latest_day_with_data) %>% 
  dplyr::group_by(trp_id) %>%
  dplyr::slice(which.min(valid_from)) %>% 
  dplyr::ungroup() %>% 
  dplyr::filter(traffic_type == "VEHICLE",
                registration_frequency == "CONTINUOUS",
                operational_status == "OPERATIONAL") %>% 
  split_road_system_reference() %>% 
  dplyr::filter(road_category != "K",
                valid_from < "2020-01-01",
                latest_day_with_data > "2021-02-01") %>% 
  dplyr::mutate(road_category = dplyr::case_when(road_category == "E" ~ "R",
                                                 road_category == "R" ~ "R",
                                                 road_category == "F" ~ "F"),
                name = stringr::str_to_title(name, locale = "no")) %>% 
  dplyr::select(trp_id, name, county_geono, county_name, municipality_name, road_category,
                road_category_and_number, road_reference, road_link_position, 
                lat, lon, latest_day_with_data)

# AADT coverage and length_quality in 2020
#trp_aadts <- trp_for_vti_tidy$trp_id %>% 
#  get_aadt_for_trp_list() %>% 
#  dplyr::filter(year == 2020)

#write.csv2(trp_aadts, file = "trp_aadts.csv", row.names = FALSE)
trp_aadts <- read.csv2("trp_aadts.csv")

# Exclude trps with low index coverage last year
# CAUTION: Problem could lie in year before last year...
pointindex <- get_published_pointindex_paginated(962, 2020, 12)

pointindices <- pointindex[[2]] %>% 
  dplyr::filter(day_type == "ALL",
                period == "year_to_date") %>% 
  dplyr::select(trp_id, index_total_coverage)

trp_for_vti_aadt <- trp_for_vti_tidy %>% 
  dplyr::left_join(trp_aadts) %>% 
  dplyr::left_join(pointindices) %>% 
  dplyr::mutate(valid_length_percent = round(valid_length_volume / adt * 100, digits = 1),
                index_ok = dplyr::case_when(is.na(index_total_coverage) ~ TRUE,
                                            index_total_coverage > 90 ~ TRUE,
                                            TRUE ~ FALSE)) %>% 
  dplyr::filter(!is.na(adt),
                coverage > 95,
                #adt >= 200,
                valid_length_percent > 99#,
                #index_ok == TRUE
                ) %>%
  dplyr::mutate(trp_label = paste(name, road_category_and_number, adt, sep = "<br/>"),
                trp_label = lapply(trp_label, htmltools::HTML))

# Write a file to manually update if the trp is chosen
# trp_for_vti_aadt %>%
#   dplyr::select(trp_id, name, county_geono, county_name, municipality_name,
#                 road_category, road_reference, adt) %>%
#   dplyr::mutate(chosen = NA) %>%
#   write.csv2(file = "trp_for_vti_2021.csv", row.names = F)

# Read back in the result of chosen trps
not_chosen <- readxl::read_xlsx("trp_for_vti_2021.xlsx") %>% 
  dplyr::filter(chosen == FALSE)

trp_for_vti_aadt <- trp_for_vti_aadt %>% 
  dplyr::filter(!(trp_id %in% not_chosen$trp_id))
```


# Punktene

```{r table}
trp_for_vti_aadt %>% 
  dplyr::select(#trp_id, 
                county_name, municipality_name, 
                name,
                road_category_and_number, 
                road_category, 
                adt) %>%
  dplyr::rename(Fylke = county_name,
                Kommune = municipality_name,
                #Punktid = trp_id,
                Navn = name,
                Veg = road_category_and_number,
                Vegkat = road_category,
                ADT = adt) %>% 
  DT::datatable(
    rownames = FALSE,
    filter = "top",
    extensions = "Buttons",
    options = list(
      dom = "Blfrtip",
      buttons = c("excel"),
      pageLength = 25,
      lengthMenu = c(25, 50, 100),
      autoWidth = TRUE))
```


# Antall punkt per fylke of vegkategori

```{r table_summary}
# TODO: add road lengths
trp_for_vti_aadt %>% 
  dplyr::group_by(county_geono, county_name, road_category) %>% 
  dplyr::summarise(n_trp = n()) %>%
  dplyr::arrange(county_geono) %>% 
  dplyr::ungroup() %>% 
  dplyr::select(-county_geono) %>% 
  tidyr::pivot_wider(names_from = road_category, values_from = n_trp) %>% 
  dplyr::rename(Fylke = county_name,
                Fylkesveg = 'F',
                Riksveg = R) %>% 
  DT::datatable(
    rownames = FALSE,
    filter = "none",
    options = list(
      dom = "t",
      pageLength = 25,
      autoWidth = TRUE))
```


# Kart

```{r map, message=FALSE, fig.height=9}
palett_adt <-
 colorNumeric(palette = "Greens",
              domain = NULL)

# TODO: county polygons (nice to have)

trp_for_vti_aadt_R <- trp_for_vti_aadt %>% 
  dplyr::filter(road_category == "R")

trp_for_vti_aadt_F <- trp_for_vti_aadt %>% 
  dplyr::filter(road_category == "F")

trp_for_vti_aadt %>% 
  leaflet(width = "100%",
          options = leafletOptions(crs = nvdb_crs,
                                   zoomControl = TRUE)) %>%
  addTiles(urlTemplate = nvdb_map_url,
           attribution = nvdb_map_attribution) %>%
  addCircleMarkers(
    data = trp_for_vti_aadt_R,
    group = "R",
    radius = 6,
    stroke = T,
    weight = 2,
    color = "#58b02c",
    opacity = 0.8,
    fill = T,
    fillColor = ~palett_adt(adt),
    fillOpacity = 0.8,
    label = ~trp_label
  ) %>%
  addCircleMarkers(
    data = trp_for_vti_aadt_F,
    group = "F",
    radius = 6,
    stroke = T,
    weight = 2,
    color = "#008ec2",
    opacity = 0.8,
    fill = T,
    fillColor = ~palett_adt(adt),
    fillOpacity = 0.8,
    label = ~trp_label
  ) %>%
  addLegend("bottomright",
            pal = palett_adt,
            values = ~adt,
            title = "ÅDT",
            opacity = 0.7,
            labFormat = labelFormat(big.mark = " ")) %>% 
  addLayersControl(
    overlayGroups = c("F", "R"),
    options = layersControlOptions(collapsed = FALSE)
  )
```


