## Gamle Kristiansand kommune
Tilsvarende resultater for gamle Kristiansand kommune angis nedenfor.

```{r}
#| label: tbl-trp_36_kommune-1
#| tbl-cap: "Tre 책rs glidende indeks for gamle Kristiansand kommune."

city_36_month_kommune |>
  dplyr::slice_max(
    month_n,
    by = year
  ) |>
  create_city_mdt_36_index_table() |>
  flextable::footnote(
    i = 1,
    j = 2,
    value = flextable::as_paragraph(
      c(tbl_cap_all_36_kommune)
    ),
    ref_symbols = c("a"),
    part = "header"
  ) |>
  flextable::fontsize(
    size = 8,
    part = "footer"
  )

```

{{< pagebreak >}}

```{r}
#| label: fig-plot_city_36_kommune
#| fig-cap: "Tidsserie med tre 책rs glidende indeks for gamle Kristiansand kommune."

visualize_city_36_mdt_index(
city_36_month_kommune,
caption_credit,
"Estimert endring i trafikkmengde siste 3 책r",
 paste0(
   "Sammenlignet med ",
   base_year
 )
)
```


```{r}
#| label: tbl-city_index_kommune
#| tbl-cap: "Estimert endring i trafikkmengde per 책r, gamle Kristiansand kommune."
#| ft.arraystretch: 0.9

if(city_number == 957) {
 city_info_kommune |>
  dplyr::filter(
    !(index_type == "chained" & month != 12)
  ) |>
  create_city_index_table_sd()
}
```


