## Om usikkerhet
Tre års glidende indeks har ganske stor usikkerhet. Dette skyldes for det meste at indekspunktene har ganske ulik trafikkutvikling i perioden. Dette igjen kommer av at det har forekommet flere større og mindre vegnettsendringer og trafikkomlegginger i perioden, som har slått ulikt ut på punktene. Data som er inkludert i beregningene, skal ha balanse mellom økt og minket trafikk i de enkelte omleggingssituasjonene, men dette fører likevel til større variasjon mellom punktene.

Et annet bidrag til usikkerheten er at det er få punkter med i beregningen. Flere punkter vil i seg selv dempe usikkerheten noe, men de vil sannsynligvis også dempe bidragene fra punktene som har størst endring.

Størrelsen på tre års glidende indeks kan avvike en del fra kjedet årlig indeks (se nedenfor) på grunn av at det er ulikt antall punkt som er med i de to beregningene. I tillegg kan trafikknedgangen og -oppgangen som inntraff henholdsvis under og etter koronapandemien ha slått litt skjevt ut på den kjedete indeksen.