## Endring i ett- og toårsperiode
Tre års glidende indeks glatter ut trender som er av kortere varighet, men som kan være synlige dersom den glidende indeksen beregnes for kortere perioder. Eksempelvis kan en økende trend i trafikken som har oppstått det siste året bli lite synlig i den tre års glidende indeksen dersom de to første årene var stabile eller hadde nedgang. For å kunne si noe om hvilken utvikling den tre års glidende indeksen kan få framover i tid, er det nyttig å se tilsvarende glidende indekser for perioder på ett og to år. Dette vises i figur @fig-rolling_indices.

```{r}
#| label: fig-rolling_indices
#| fig-cap: "Tidsserier med ett, to og tre års glidende indeks."
#| fig-dpi: 300

visualize_rolling_indices(
  rolling_indices_long,
  caption_credit,
  "Estimert gjennomsnittlig endring siste glidende 1, 2 og 3 år",
  paste0(
    "Sammenlignet med ",
    base_year
  )
)
```

Dersom trafikkmengden i årene framover blir liggende på samme nivå som i dag, vil det glidende gjennomsnittet for både 2 og 3 år sammenfalle med det som gjennomsnittet for 1 år ligger på i dag.

{{< pagebreak >}}