## Gjennomgangstrafikk {#sec-through_traffic}
En analyse gjennomført av Statens vegvesen viser at andelen gjennomgangstrafikk i byområdet er så liten at den ikke har innvirkning på byindeksen.


## Ny bomring 2018
38 nye bomstasjoner ble satt i drift 1. oktober 2018 i Stavanger sentrum, Sandnes sentrum, Stavanger lufthavn Sola, Forus, Risavika og på grensen mellom Stavanger og Randaberg. Dette førte til noe omfordeling av trafikken i området.


## Åpning av Ryfast 2019 og 2020
Åpningen av Ryfast ble gjort 30. desember 2019 (Ryfylketunnelen) og 22. april 2020 (Eiganestunnelen og Hundvågtunnelen). Dette førte til omfordeling av trafikken på flere veger i området. Blant annet ble deler av gamle E39 omklassifisert til fv. 440.

Trafikkregistreringspunkter som direkte er påvirket av dette:

  - fv. 4566 Bybrua sør
  - fv. 4564 Storhaugtunnelen
  - fv. 441 Kannik
  - fv. 4570 Randabergveien

Disse er utelatt fra den årlige indeksen i ett år fra åpningen. Og siden disse vegene permanent har fått mindre trafikk er de tatt helt ut av beregningen av tre års glidende indeks.


## Vedlikeholdsarbeid i Byhaugtunnelen 2020-2022
I perioden 23.11.2020 til 09.12.2022 var E39 Byhaugtunnelen (Ytre ringveg vest) stengt på grunn av vedlikeholdsarbeid. Dette førte til noe økt trafikk i fv. 4570 Randabergveien. Dette trafikkregistreringspunktet er derfor ekskludert i denne perioden samt ett år etter gjenåpning.


## Fv. 44 Åsedalen
En stor del av trafikken som tidligere gikk om fv. 44 Jærveien i Åsedalen går nå i stedet på fv. 4490 Hoveveien etter at denne ble koblet direkte på E39 ved Hove. Åpningen av denne nye snarvegen skjedde 26. oktober 2018. Derfor er punktet Åsedalen tatt helt ut av beregningen av tre års glidende indeks.


## Fv. 44 Strandgata
I perioden fra februar 2023 til desember 2024 er fv. 44 stengt nord for Sandnes sentrum. Strandgata er etter dette permanent stengt for gjennomgangstrafikk, og punktet her er derfor ikke lenger med i indeksen.
