## Gjennomgangstrafikk {#sec-through_traffic}
Blant de 28 byindekspunktene er det fire som har en andel gjennomgangstrafikk som ikke er helt ubetydelig. Basert på analyser utført ved hjelp av en regional transportmodell er det estimert følgende andeler for gjennomgangstrafikk:

- rv. 658 Ellingsøytunnelen: 15 %
(dette gjelder også punktet Avkjøring Ålesundstunnelene øst, på rampen fra E136)
- E39 Moatunnelen: 10-20 %
- E39 Blindheimstunnelen: i overkant av 20 %

Andelene viser at det er lokaltrafikken som dominerer også her. Dersom endringen i lokaltrafikken er relativt liten, vil en eventuell endring i gjennomgangstrafikken gi utslag for disse punktene. Men sett i sammenheng med de øvrige punktene i byområdet, vil likevel en endring i gjennomgangstrafikken ha en relativt liten betydning for byindeksen.


## Bompengeinnkreving
I Ålesund ble bompengeinnkreving satt i drift i august 2022. 


## E136 Breivika-Lerstad
På strekningen mellom Breivika og Lerstad skal det bygges ny E136 som skal stå ferdig i 2027. Dette vil avlaste dagens E136 Borgundvegen og fv. 534 Lerstadvegen på samme strekning.

I 2025 ble det gjort en større trafikkomlegging i forbindelse med prosjektet. Dette har ført til at kjøremønsteret har endret seg for deler av trafikken.

Disse punktene antas å ha fått mindre trafikk:

- Lerstad-Volsdalen
- Nørvasundet arm Borgundvegen-Moa
- Nørvasundet nord Lerstad-Borgund
- Skuggentunnelen
- Volsdalen-Lerstad

Disse punktene antas å ha fått mer trafikk:

- Borgundgavelen
- Kolvikbakken ungdomsskole
- Nørvasundet arm Ålesund-Borgundvegen
- Nørvasundet nord Borgund-Ålesund
- Volsdalen rampearm
- Ålesund-Volsdalen

Omleggingen vil sannsynligvis vare til 2027 når nytt vegsystem åpner i sin helhet. Det er vurdert at punktene i sum ikke fører til en betydelig skjevhet i utvalg av punkter, og de er derfor med i indeksen.


## E136 Moa-Åse
I forbindelse med bygging av kollektivknutepunkt og gang- og sykkelveg langs E136 har punktene Moa vest og Borgundvegen fått mindre trafikk enn normalt i 2024. Punktet Moa nord har fått mer trafikk. 


## Arbeider krysset Alvikvegen/Brusdalsvegen
Sommeren 2025 foregikk det arbeider i krysset mellom fv. 5946 Alvikvegen og fv. 5948 Brusdalsvegen. Dette førte til mer trafikk i Høgvollstubben og Moa nord. Disse punktene er utelatt fra indeksen i denne perioden.
