## Gjennomgangstrafikk {#sec-through_traffic}
En analyse gjennomført av Statens vegvesen viser at andelen gjennomgangstrafikk i byområdet er så liten at den ikke har innvirkning på byindeksen.


## Carl Konows gate stengt i 2020
I store deler av 2020 var Carl Konows gate stengt for gjennomkjøring. Dette førte til en omfordeling av trafikken i registreringspunktene ved Gyldenpris og Damsgårdsveien. Disse punktene har derfor indeksverdier som avviker fra de andre, men dekker samlet sett utviklingen i området.


## Ny E39 Svegatjørn - Rådal
Ny E39 mellom Svegatjørn og Rådal ble åpnet 31. oktober 2022. Dette avlastet omkringliggende vegnett, deriblant den opprinnelige strekningen på E39 gjennom Kaland og Syfteland. En omfordeling av trafikken oppsto også i områdene Nesttun, Sørås samt til Fana og Nordvik. Trafikken som går på nyvegen er ikke en del av datagrunnlaget til byindeksen, og derfor må de byindekspunktene som står på avlastede veger holdes utenfor den årlige indeksen en periode. Siden indeksberegningene sammenligner trafikk mellom to påfølgende år, må også et år etter åpning utelates for disse punktene før indeksen sammenligner trafikk med samme vegnett som året før. 

Derfor er følgende indekspunkter holdt utenfor i perioden november 2022 - oktober 2023:

  - E39 Røykenes
  - E39 Vallaheiane
  - E39 Nesttuntunnelen
  - E39 Troldhaugtunnelen - Lagunen
  - rv. 508 Lagunen - Troldhaugtunnelen og Sørås
  - fv. 546 Fana ved Kirkevoll
  - fv. 5158 Nordvik
  
  For den tre års glidende indeksen kan de samme punktene ikke lenger inngå i datagrunnlaget fra og med november 2022.

