## Gjennomgangstrafikk {#sec-through_traffic}
En analyse gjennomført av Statens vegvesen viser at andelen gjennomgangstrafikk i byområdet er så liten at den ikke har innvirkning på byindeksen.


## Sikkerhetsoppgradering tunneler 2023-2025
På grunn av oppgraderingsarbeider er Breivik-, Hansjordnes- og Mellomtunnelen stengt i perioden fra 21. august 2023 til desember 2024. 

Alternative ruter parallelt med Breiviktunnelen passerer indekspunktene i Dramsvegen og Stakkevollvegen. Disse får da økt trafikk, uten at dette kompenseres for med nedgangen (til null) i punktet i Breiviktunnelen (som er ute av drift). Disse punktene holdes derfor utenfor indeksen i denne perioden. 

Punktet i Sentrumstangenten holdes også utenfor indeksen da det ikke er indekspunkt på alternative ruter parallelt med denne strekningen.


## Vedlikeholdsarbeid Tromsøbrua 2024
I perioden fra midten av juni til midten av august 2024 var Tromsøbrua delvis eller helt stengt på grunn av vedlikeholdsarbeid. Punktet her er utelatt fra indeksen i disse månedene. Det samme gjelder punktene Kraftforsyningen og Breivika, samt Tromsøysundtunnelene. Dette er fordi endringen i trafikkstrømmene ikke fanges opp på en balansert måte i denne perioden.