## Gjennomgangstrafikk {#sec-through_traffic}
En overordnet analyse gjennomført av Statens vegvesen viser at andelen gjennomgangstrafikk i byområdet er relativt liten, og det antas at den ikke har særlig innvirkning på byindeksen. For å kunne beregne byindeks uten at gjennomgangstrafikk er med i datagrunnlaget, må gjennomgangstrafikk estimeres på hvert enkelt rutevalg for alle kombinasjoner av veger inn og ut av området. For Osloområdet, som har stor geografisk utstrekning og mange alternative ruter, er dette en krevende og detaljert analyse. Vurderingen er derfor i stedet basert på gjennomgangtrafikkens totale andel av trafikkarbeidet i området. Andelen og endringen i gjennomgangstrafikk er vurdert til å gi ubetydelig bidrag til byindeksen.


## Vålerengtunnelen stengt juni 2020 - juni 2021
I perioden hvor deler av Vålerengtunnelen var stengt er punktet på E6 ved Helsfyr utelatt fra beregningene.


## Nordbytunnelen stengt høsten 2018
I perioden da Nordbytunnelen var delvis stengt høsten 2018 er punktene "Nessetveien" og "Nordbytunnelen" tatt ut av beregningene.


## Anleggsarbeid på E18 ved Bygdøy og Sjølyst
I perioden juli - oktober 2023 foregikk det anleggsarbeider på E18 ved Bygdøy og Sjølyst. Anbefalt omkjøring var Ring 3. I denne perioden er noen trafikkregistreringspunkter utelatt for at omfordelingen av trafikk skal være balansert i datagrunnlaget.


## Oppgradering av tunneler på rv. 162 Ring 1
Fra 1. juli 2024 til sommeren 2027 er rv. 162 Ring 1 mellom Oslo Spektrum i øst og Pilestredet/ St. Olavsgate i vest stengt for all trafikk. Trafikkregistreringspunktene i Kong Håkon 5.s gate, Maridalsveien og Finnmarksgata er utelatt fra indeksen i denne perioden.


## Innsnevring Ring 3 april og mai 2024
På rv. 150 Ring 3 mellom Ullevål og Nydalen var det i april og mai 2024 innsnevring fra 4 til 2 kjørefelt. Dette førte til en omfordeling av trafikken. Punktene ved Grefsen og Gaustad er utelatt fra indeksen i denne perioden. Det er ingen punkt på Ring 2 med data i denne perioden.


## Stengt pårampe fra Starveien til E6 i kryss 42
Pårampen fra Starveien og ut på E6 var stengt i perioden juli-november 2024. Dette førte til mer trafikk på punktene Karihaugen rampe mot Furuset, Østre Aker vei og Østre Aker vei rampe mot Hvam. Disse er utelatt fra datagrunnlagt i denne perioden.


## Arbeider i Griniveien
Fra oktober 2023 og ut 2025 foregår det arbeider i fv. 168 Griniveien mellom Røakrysset og Ekraveien. Redusert framkommelighet her betyr at punktet Grini får mindre trafikk enn normalt. Trafikken som vanligvis går her må nå velge andre alternativer for kryssing mellom Bærum og Oslo (Lysakerelva). Det er da følgende alternativer:

- fv. 160 Bærumsveien med punktet Oslo grense
- rv. 150 Granfosstunnelen (ring 3) med punktene i Granfosstunnellen
- E18 ved Lysaker med punktet Lysakerlokket.

Punktet Oslo grense holdes utenfor indeksen i denne perioden. Ved punktene i Granfosstunnelen og Lysakerlokket blandes trafikken fra så mange andre steder at effekten av dette enkelttiltaket neppe er utslagsgivende, og derfor beholdes disse punktene i indeksen.

Punktet Vollsveien får også mye av omkjøringstrafikken, og holdes utenfor indeksen.

Punktet Vækerøveien v/Ullernchausseen mangler mye data fra før, så dette punktets bidrag til indeksen påvirkes ikke av dette arbeidet.