## Utvidelse av rv. 110 mellom Ørebekk og Simo
Utbygging av rv. 110 ble startet opp våren 2016 og ble åpnet i november 2019. Punktet "Simo"  som registrerte trafikk på den opprinnelige vegen bidro med data til indeksen ut 2018. Dette punktet ble ved slutten av 2019 erstattet av et nytt punkt på den nye vegen, og dette har bidratt med data til indeksen fra og med 2021.

Punktet på fv. 381 Veumveien hadde i referanseåret en andel av trafikken som i dag går på utvidet rv. 110 forbi Simo i stedet. Veumveien er derfor ikke med i beregningene av treårs glidende indeks. Det er også holdt utenfor årlig indeks i perioden november 2019 - november 2020.


## Kråkerøy bru stengt
I perioden 23. august 2021 - 22. oktober 2021 var Kråkerøy bru stengt på grunn av vedlikeholdsarbeid. Trafikken gikk i stedet via Værstebrua. Trafikkregistreringspunktene på disse to bruene vil til sammen registrere all trafikk til og fra Kråkerøy og Hvaler, men siden det ikke er data fra Kråkerøy bru i denne perioden vil ikke indeksen fange opp dette og punktene er derfor holdt utenfor i disse tre månedene.


## Rv. 22 stengt ved Moumbekken bru
I perioden fra 17. august til 11. september 2022 var Moumbekken bru på rv. 22 stengt. I denne perioden er data fra punktet Hvitsten tatt ut av beregningene.


## Rolvsøysund bru
Trafikkregistreringspunktet ved Rolvsøysund bru har tidvis en del lengdemålinger som ikke er godkjent. Dette gjaldt også referanseåret 2016. Dette fører til at data fra punktet ikke er av god nok kvalitet til å inngå i den tre års glidende indeksen.