## Gjennomgangstrafikk {#sec-through_traffic}
En analyse gjennomført av Statens vegvesen viser at gjennomgangstrafikk utgjør omkring 20 % av alt trafikkarbeid i Buskerudbyen. E18 mellom nord og sør har halvparten av dette, men det er flere hovedfartsårer inn og ut av området og dermed mange mulige gjennomkjøringsruter.  Dette gjør det vanskelig å anslå andelen gjennomgangstrafikk på den enkelte vegstrekning, som er en forutsetning for å kunne justere byindeksen.


## Strømsåstunnelen stengt i januar og februar 2017
Når Strømsåstunnelen var stengt i januar og februar 2017, var punktet her uten trafikk og ble helt ekskludert fra indeksen i denne perioden. Da gikk trafikken i stedet på parallellveiene og følgende punkter fikk dermed en økning i trafikken: Bj. Bjørnsonsgt., Kreftingsgate, Øvre Sund bru, Gulskogen, Landfalløya bru syd, Travbanen, Herstrøm og Daler. Den aktuelle perioden er derfor ekskludert også for disse punktene for å unngå at punktene måler en ensidig økning, når det ikke er tilsvarende nedgang på punktet i Strømsåstunnelen.


## Ny E134 forbi Kongsberg
Fredag 3. juli 2020 ble ny E134 åpnet forbi Kongsberg. Punktene Gamle Kongsberg Kro og Veungsdalen som ligger der hvor E134 gikk tidligere, men som nå ligger på fylkesveg, tas ut av byindeksen ett år for å unngå at trafikkomleggingen slår ut som en generell nedgang i trafikken i området. Det samme gjelder punktet Krekling på fv. 286. Disse tre punktene tas helt ut av beregningen av den tre års glidende indeksen etter åpningen.


## Ny Asdøla bru på fv. 285
I november og desember 2021 og deler av mai 2022 var fv. 285 stengt ved Asdøla på grunn av bygging av ny bru. Punktet "Lierbyen nord" er holdt utenfor indeksen i dette tidsrommet.


## Flom august 2023
Deler av E134 var stengt i flere dager i august 2023 på grunn av flom. I denne perioden er noen av trafikkregistreringspunktene på veger som var åpne holdt utenfor indeksen for å unngå overtelling av trafikk som fulgte omkjøringsrutene.

 
## Ny bybru
Bybrua i Drammen ble stengt for trafikk i mai 2022 og revet. Ny bybru med samme beliggenhet åpnet for trafikk i oktober 2025. Både før og etter stenging var Bybrua forbeholdt gående, syklende og kollektivtransport. Taxier kan benytte brua. Stenging og gjenåpning av Bybrua vurderes likevel å ha ubetydelig innvirkning på byindeksen. I anleggsperioden var også Øvre/Nedre Strandgate stengt for gjennomkjøring. Før stenging var denne gata åpen for all trafikk. Etter gjenåpningen av Bybrua er den i tråd med politisk vedtak kun åpen for gjennomkjøring ved bruenden/Bragernes torg med buss. Avslutningen av anleggsperioden endret derfor ikke forholdene for personbiler i denne gata.

 
## Nytt sykehus på Brakerøya
Nytt sykehus på Brakerøya i Drammen åpnet i 2025, med full drift fra oktober. Med dette ble en av Buskeruds største arbeidsplasser flyttet fra sin gamle lokasjon rett vest for Drammen sentrum til Brakerøya. Flyttingen har hatt konsekvenser for den lokale trafikkavviklingen, og kan ha påvirket de nærliggende byindekspunktene Bragernestunnelen og Rosenkrantzgata noe. Trafikktallene for de siste månedene i 2025 tilsier imidlertid ikke endring av en størrelsesorden som gir behov for å ta ut noen av punktene fra byindeksen.