## Gjennomgangstrafikk {#sec-through_traffic}
En analyse gjennomført av Statens vegvesen viser at andelen gjennomgangstrafikk i byområdet er så liten at den ikke har innvirkning på byindeksen.


## Anleggsarbeid på fv. 6680 Tillerbrua - Klæbu
Det har i flere perioder vært anleggsarbeid med helt stengt veg på fv. 6680 mellom Tillerbrua og Klæbu sentrum. Trafikken på denne strekningen har i disse periodene i stedet gått over fv. 704 forbi Torgårdsletta. Til sammen fanger de to bomstasjonene her opp den totale trafikken mellom Trondheim og Klæbu.


## Bygging av Nydalsbrua ved Sluppen
Den første trafikkomleggingen av betydning i dette byggeprosjektet var stenging av nordgående avkjøring fra E6 ved Kroppan til rv. 706 (kryssnummer 35). Trafikken som vanligvis benyttet denne avkjøringen, måtte i stedet benytte avkjøring i kryssnummer 34 på Tonstad eller kryssnummer 37 ved Nidarvoll og Sluppen og kjøre tilbake over Sluppen bru. Sistnevnte trafikk kom da tilbake til enten bomstasjonen "Bjørndalen (Oslovn.)" eller trafikkregistreringspunktet "Oslovegen" som normalt, men har i tillegg passert bomstasjonen "Nord for Sluppen bru". Dette medførte en liten økning i antall passeringer på denne bomstasjonen som gjenspeiler en noe forlenget kjørerute for denne trafikken, og som derfor er beholdt i datagrunnlaget.

Den neste store trafikkomleggingen skjedde 19. mars 2021 med stengingen av rv. 706 rett sør for Sluppen bru. Dette påvirket direkte bomstasjonen "Bjørndalen (Oslovn.)" som ikke har noe data for denne perioden. Bomstasjonen "Nord for Sluppen bru" og trafikkregistreringspunktet "Oslovegen" var i denne perioden på samme strekning (ingen kryss mellom) og derfor er kun bomstasjonen "Nord for Sluppen bru" beholdt i datagrunnlaget.

Fra 5. mai 2021 ble rv. 706 ved Sluppen bru stengt på grunn av fare for ras, og vegen forble stengt i en periode mens forholdene ble utbedret. I denne perioden er punktet "Oslovegen" og bomstasjonen "Nord for Sluppen bru" helt uten trafikk. I tillegg er trafikken gjennom Marienborgtunnelen en del redusert. Det er rimelig å anta at trafikken som normalt går forbi disse punktene velger omkjøringsruter som er dekket av andre punkter.

Fra 23. juni 2021 ble rv. 706 gjenåpnet nord for Sluppen bru, før den igjen ble stengt i perioden 1. juli til 14. august 2021.

Fra 21. august 2021 ble rv. 706 gjenåpnet også sør for Sluppen bru.

Fra 3. januar 2022 og til 14. august 2023 var rv. 706 stengt nord for Sluppen bru. I denne perioden er det kun bomstasjonen "Nord for Sluppen bru" som bidrar med data til indeksen, og ikke bomstasjonen "Bjørndalen (Oslovn.)" eller trafikkregistreringspunktet "Oslovegen".

Fra og med 26. juni 2023 ble Sluppen bru stengt for biltrafikk. Bomstasjonen "Nord for Sluppen bru" var ikke lenger operativ etter dette.

Fra 14. august 2023 ble Oslovegen gjenåpnet fra sør til nord forbi Sluppen bru. Bomstasjonen som tidligere sto "Nord for Sluppen bru" på veg til Sluppen er etter dette flyttet til Oslovegen nord for Sluppen bru. Trafikk fra denne bomstasjonen er dermed ikke sammenlignbar før og etter dette tidspunktet.

I perioden 11. september 2023 til 15. oktober 2023 var kryss på kv. 7440 på Sluppen stengt. Dette førte til mindre trafikk gjennom bomstasjonen i Tempevegen. Denne trafikken vil i stedet ha passert en av bomstasjonene på E6 eller i Bratsbergvegen.

Nydalsbrua og tilhørende veger ble åpnet 16. oktober 2023.

I perioden fra mars 2021 til oktober 2023 kan byindeksen være noe kunstig høy. Dette skyldes at flere punkter har fått mer trafikk enn det antallet punkter som har fått mindre trafikk som følge av vegstengingene i anleggsperioden. For å unngå dette måtte de fleste punktene i Trondheim by ha vært ekskludert i denne perioden.


## Bygging av Saupstadbrua
I perioden 14. november 2021 til 29. april 2022 var Fv 6682 i Bjørndalen stengt like nord for krysset med fv. 6688 grunnet bygging av ny gang- og sykkelbru. Dette påvirket byindekspunktene i liten grad.


## Bygging av Gryta parkeringskjeller
I perioden fra november 2020 til november 2022 foregikk det byggearbeider ved fv. 6692 ved Gryta utenfor Trondheim sentralstasjon. Dette påvirket trafikken ved punktene på Jernbanebrua og Brattørbrua. Det antas at disse to punktene oppveide hverandre i byggeperioden, da mye av trafikken som normalt går over Jernbanebrua i stedet gikk over Brattørbrua. En større omlegging av trafikken begynte i februar 2021. I månedene desember 2021 til februar 2022 var punktet på Jernbanebrua ute av drift og derfor er også punktet på Brattørbrua ekskludert fra datagrunnlaget for at ikke trafikkomleggingen skal påvirke byindeksen ensidig som en økning. Fra og med mars 2022 er det sammenlignbare forhold med foregående år, slik at kun punktet på Brattørbrua er med i datagrunnlaget fram til november 2022. Så lenge punktet Jernbanebrua er ute av drift etter åpning av vegen i området, vil Brattørbrua holdes utenfor indeksen, inntil ett år etter åpning, fram til november 2023.


## Arbeider i Breidablikveien
Kv. 1184 Breidablikveien er stengt mellom fv. 6650 Byåsveien og kv. 8165 Viktor Baumannsvei i perioden januar - august 2025. I denne perioden er punktet i Byåsveien ved Nyveibakken ikke med i indeksen fordi en del av trafikken som normalt går her i stedet velger Roald Amundsvei (Vestoppfarten).


## Arbeider i Strindheimtunnelen
Fra 12. mai 2025 er det ene løpet i Strindheimtunnelen stengt, mens det andre løpet er åpent for tovegstrafikk. Dette medfører redusert kapasitet og en del av trafikken som går øst-vest velger andre ruter. I denne perioden er punktene i Bøckmans veg og Oslovegen utelatt.
