## Gjennomgangstrafikk {#sec-through_traffic}
En overordnet analyse gjennomført av Statens vegvesen viser at andelen gjennomgangstrafikk i byområdet er relativt liten. Det er E18/E39 som har størst andel gjennomgangstrafikk, men den er fortsatt relativt liten sammenlignet med den lokale trafikken. Når disse punktene også vektes sammen  med øvrige punkt som kun har lokaltrafikk, vurderes gjennomgangstrafikk til å gi et ubetydelig bidrag til byindeksen. I tillegg har endringen i gjennomgangstrafikk vært liten.


## Ny E39 Kristiansand vest - Mandal øst
Ny strekning på E39 mellom Kristiansand og Mandal åpnet 24. november 2022. Punktene Lindeli, Mjåvann og Volleberg blir holdt utenfor den årlige indeksen i en periode på ett år etter åpningen. I den tre års glidende indeksen kan ikke lenger punktene inngå etter åpningen.


## Vegarbeid på fv. 488 og fv. 490
På grunn av utskifting av kommunale vann- og avløpsrør i Marviksveien og andre arbeider på fv. 490 er punktet Østre Ringvei sør utelatt i hele 2023.