## Gjennomgangstrafikk {#sec-through_traffic}
En analyse gjennomført av Statens vegvesen viser at andelen gjennomgangstrafikk i byområdet er relativt liten. Det er kun E6 som har en betydelig andel gjennomgangstrafikk, og derfor er det ikke tatt med noen byindekspunkt fra denne vegen. Øvrige ruter for gjennomgangstrafikk har relativt lite trafikk sammenlignet med den lokale trafikken. Når disse punktene også vektes sammen med øvrige punkt som kun har lokaltrafikk, vurderes gjennomgangstrafikk til å gi et ubetydelig bidrag til byindeksen.


## Bomstasjoner
I perioden fra januar til mai 2023 var det åtte operative bomstasjoner rundt sentrale deler av Fredrikstad by. Av disse var seks bomstasjoner tilhørende Bypakke Nedre Glomma fase 1. I tillegg var det to bomstasjoner på Kråkerøyforbindelsen. Fase 1 ble avsluttet 31. mai 2023 og i perioden fra juni 2023 til mars 2024 var det kun de to bomstasjonene på Kråkerøyforbindelsen som var operative. 20. mars 2024 startet innkrevingen for fase 2 av Bypakke Nedre Glomma med 23 bomstasjoner i Fredrikstad og Sarpsborg. Med de to bomstasjonene på Kråkerøyforbindelsen er det totalt 25 bomstasjoner i drift rundt Fredrikstad og Sarpsborg.

Innkrevingen på de to bomstasjonene knyttet til Kråkerøyforbindelsen ble avsluttet 7. februar 2025. Dette er trolig en del av forklaringen på økningen vi ser i punktene på fv. 108 Kråkerøy bru og fv. 108 Værstebrua for perioden jan-apr 2024-2025.


## Rolvsøysund bru
Trafikkregistreringspunktet ved Rolvsøysund bru har tidvis en del lengdemålinger som ikke er godkjent. Dette fører til at data fra punktet ikke er av god nok kvalitet til å inngå i den tre års glidende indeksen.


## Gravearbeider Opstadveien
Fra januar 2024 til sommeren 2025 er den kommunale Opstadveien stengt grunnet gravearbeider. Trafikken som vanligvis bruker denne til gjennomkjøring, benytter i stedet fv. 114 forbi punktet i Greåkerdalen. Dette punktet holdes derfor utenfor indeksen i denne perioden.


## Gravearbeider Fredrikstad sentrum
I 2024 foregikk det diverse gravearbeider i Fredrikstad sentrum som førte til at mer trafikk måtte kjøre rundt om rv. 110 forbi punktet St. Hansfjellet. Dette punktet holdes derfor utenfor indeksen i denne perioden.


## Arbeider rv. 22 Hafslunds gate
Riksveg 22 utvides fra to til fire felt på strekningen mellom Hafslund skole og Dondern. Arbeidet hadde oppstart i 2025. Punktet Hafslund øst er ikke med i indeksen så lenge anleggsarbeidet pågår. 